### PR TITLE
feat: implement shiftLeft function push down

### LINKED ISSUE #5099: Implement `LeftShift` function push down
## Feature Request

**Describe the feature you'd like:**

We'd like to support `LeftShift` function push down.

**Teachability, Documentation, Adoption, Migration Strategy:**

At least one integration test and several unit tests.

### PR DESCRIPTION
**Pull request by AnnieoftheStars**
### What problem does this PR solve?

Issue Number: close #5099

related pr: https://github.com/pingcap/tidb/pull/36677

Problem Summary:

implement shiftLeft function push down

### What is changed and how it works?

1. Register bitShiftLeft func name in scalar_func_map.
2. update `DAGExpressionAnalyzerHelper::function_builder_map`,  wrap `bitShiftLeft` builder with buildBitwiseFunction.
3. Referring to [shiftRight](https://github.com/pingcap/tiflash/pull/5156) implementation and [cppRef](https://en.cppreference.com/w/cpp/language/operator_arithmetic), update original BitShiftRightImpl to handle a C++ undefined behavior of shift operation.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Support to pushdown shiftLeft to TiFlash
```

### CODE REVIEW

**Comment by Willendless** [comment]
Thanks for your contribution, excellent job!

**Comment by Willendless** [comment]
According to https://github.com/pingcap/tiflash#contributing, you can try

```shell
cd $WORKSPACE/tiflash
python3 format-diff.py --diff_from `git merge-base ${TARGET_REMOTE_BRANCH} HEAD`
```

to format your code :)

**Comment by AnnieoftheStars** [comment]
> According to https://github.com/pingcap/tiflash#contributing, you can try
> 
> ```shell
> cd $WORKSPACE/tiflash
> python3 format-diff.py --diff_from `git merge-base ${TARGET_REMOTE_BRANCH} HEAD`
> ```
> 
> to format your code :)

okay.

**Review by Willendless — APPROVED** [review]

**Review by wshwsh12 — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]
LGTM

**Pull request merged**
