### PR TITLE
fix: mitigate old docker for full stack test

### PR DESCRIPTION
**Pull request by lijie0123**
Signed-off-by: lijie <lijie@pingcap.com>

### What problem does this PR solve?

Fix integration test in CI because docker is too old

Issue Number: ref #6233

Problem Summary: 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by hongyunyan — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]

**Comment by xzhangxian1008** [comment]
please open an issue and link to it

**Pull request merged**
