### PR TITLE
*: Use static to avoid thread-wise memtrace lifetime problem

### LINKED ISSUE #9038: Panic when allocate memory
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```

    
{"namespace":"endless-htap-spill-random-failpoint-tps-7578098-1-153","level":"ERROR","log":"[BaseDaemon.cpp:560] [\"
       0xb34613d    faultSignalHandler(int, siginfo_t*, void*) [tiflash+187982141]
                    libs/libdaemon/src/BaseDaemon.cpp:211
  0x7f189d080db0    <unknown symbol> [libc.so.6+347568]
       0xb6d20dc    std::__1::shared_ptr<DB::JointThreadInfoJeallocMap>::operator->() const [tiflash+191701212]
                    /usr/local/bin/../include/c++/v1/__memory/shared_ptr.h:586
       0xcbe183c    DB::KVStore::reportThreadAllocBatch(std::__1::basic_string_view<char, std::__1::char_traits<char> >, DB::ReportThreadAllocateInfoBatch) [tiflash+213784636]
                    dbms/src/Storages/KVStore/KVStore.cpp:500
       0xcc493b5    ReportThreadAllocateBatch [tiflash+214209461]
                    dbms/src/Storages/KVStore/FFI/ProxyFFI.cpp:1065
  0x7f18a6b9fad3    proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::directly_report_jemalloc_alloc::_$u7b$$u7b$closure$u7d$$u7d$::h5a934a3fae521d24 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158964435]
                    contrib/tiflash-proxy/proxy_components/proxy_ffi/src/[engine_store_helper_impls.rs:126](http://engine_store_helper_impls.rs:126/)
  0x7f18a6b61db9    std::thread::local::LocalKey$LT$T$GT$::try_with::h2738826456343c58 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158711225]
                    /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/[local.rs:446](http://local.rs:446/)
  0x7f18a6b613d4    std::thread::local::LocalKey$LT$T$GT$::with::h2465f6bf8302d3ab [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158708692]
                    /rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/thread/[local.rs:422](http://local.rs:422/)
  0x7f18a6b8d5b5    proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::directly_report_jemalloc_alloc::hdd4749ff932e4711 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158889397]
                    contrib/tiflash-proxy/proxy_components/proxy_ffi/src/[engine_store_helper_impls.rs:111](http://engine_store_helper_impls.rs:111/)
  0x7f18a6b8d93f    proxy_ffi::engine_store_helper_impls::_$LT$impl$u20$proxy_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::handle_get_engine_store_server_status::ha6984cf31bf144cc [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+158890303]
                    contrib/tiflash-proxy/proxy_components/proxy_ffi/src/[engine_store_helper_impls.rs:189](http://engine_store_helper_impls.rs:189/)
  0x7f18a1c1747d    proxy_server::run::run_impl::h962ac6a36e3ad152 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+75568253]
                    contrib/tiflash-proxy/proxy_components/proxy_server/src/[run.rs:267](http://run.rs:267/)
  0x7f18a1c29b92    proxy_server::run::run_tikv_proxy::h720991976c6255d7 [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+75643794]
                    contrib/tiflash-proxy/proxy_components/proxy_server/src/[run.rs:389](http://run.rs:389/)
  0x7f18a1c0906c    proxy_server::proxy::run_proxy::h94e865f8dce71ddb [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+75509868]
                    contrib/tiflash-proxy/proxy_components/proxy_server/src/[proxy.rs:325](http://proxy.rs:325/)
  0x7f18a0aea0e8    run_raftstore_proxy_ffi [[libtiflash_proxy.so](http://libtiflash_proxy.so/)+57557224]
                    contrib/tiflash-proxy/raftstore-proxy/src/[lib.rs:19](http://lib.rs:19/)
       0x48e2632    DB::RaftStoreProxyRunner::runRaftStoreProxyFFI(void*) [tiflash+76424754]
                    dbms/src/Server/Server.cpp:530
  0x7f189d0cb802    start_thread [libc.so.6+653314]\"] [source=BaseDaemon] [thread_id=118]","pod":"tc-tiflash-0","container":"data0"}
```

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #9038

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
https://github.com/CalvinNeo/tics/pull/8

I've created a PR for refining code in JointThreadInfoJeallocMap

**Comment by CalvinNeo** [comment]
> [CalvinNeo#8](https://github.com/CalvinNeo/tics/pull/8)
> 
> I've created a PR for refining code in JointThreadInfoJeallocMap, PTAL

Adopted

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
