### PR TITLE
update TiFlash proxy

### LINKED ISSUE #4906: PD store usage not right in master.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- The tiflash used from tiflash metrics
image

- The metrics from pd
image

They both called `getFsStats()`. And but get the different result.
I think the problem in pd.rs `handle_store_heartbeat`:
```
let capacity = store_stats.fs_stats.capacity_size;
        let available = store_stats.fs_stats.avail_size;
        stats.set_used_size(store_stats.fs_stats.used_size);
        stats.set_capacity(capacity);

        let used_size = self.snap_mgr.get_total_snap_size().unwrap()
            + store_info
                .kv_engine
                .get_engine_used_size()
                .expect("kv engine used size")
            + store_info
                .raft_engine
                .get_engine_size()
                .expect("raft engine used size");
        stats.set_used_size(used_size);
```
The below set_used_size replace the origin one.

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What problem does this PR solve?

Issue Number: close #4906

Problem Summary:
Current version of proxy merges TiKV 6.0. Some TiKV code will modify `store_stats` after it is reported by `handle_compute_store_stats`.
These modification shall be disabled, since store status on TiFlash side rather than Proxy's side matters.

### What is changed and how it works?
Disable newly added code by TiKV.

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by jiaqizho — APPROVED** [review]

**Review by lidezhu — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
Seems that there is compile error for proxy code?
https://github.com/pingcap/tidb-engine-ext/runs/6464382882?check_suite_focus=true
```
error[E0425]: cannot find value `used_size` in this scope
    --> components/raftstore/src/store/worker/pd.rs:1115:18
     |
1115 |             .set(used_size as i64);
     |                  ^^^^^^^^^ not found in this scope

    Checking tidb_query_aggr v0.0.1 (/home/runner/work/tidb-engine-ext/tidb-engine-ext/components/tidb_query_aggr)
    Checking tidb_query_executors v0.0.1 (/home/runner/work/tidb-engine-ext/tidb-engine-ext/components/tidb_query_executors)
warning: unused import: `ImportExt`
  --> components/raftstore/src/store/snap/io.rs:12:57
   |
12 |     CfName, EncryptionKeyManager, Error as EngineError, ImportExt, IngestExternalFileOptions,
   |                                                         ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `IngestExternalFileOptions`
  --> components/raftstore/src/store/snap/io.rs:12:68
   |
12 |     CfName, EncryptionKeyManager, Error as EngineError, ImportExt, IngestExternalFileOptions,
   |                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0[425](https://github.com/pingcap/tidb-engine-ext/runs/6464382882?check_suite_focus=true#step:6:425)`.
warning: `raftstore` (lib) generated 2 warnings
error: could not compile `raftstore` due to previous error; 2 warnings emitted
```

**Pull request merged**
