### PR TITLE
update proxy of release-8.1 to raftstore-proxy-8.1

### LINKED ISSUE #9410: update proxy on release-8.1
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #9410 ref #4982, close https://github.com/pingcap/tiflash/issues/9287

Problem Summary:
 update proxy to raftstore-proxy-8.1

### What is changed and how it works?

update proxy to raftstore-proxy-8.1, which include the BR restore pre-check capabilities

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by CalvinNeo** [comment]
Proxy https://github.com/pingcap/tidb-engine-ext/compare/7dc50b4eb06124e31f03adb06c20ff7ab61c5f79...561447429488df40c174193f15f391459f307a40

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Comment by CalvinNeo** [comment]
DMStoreForSegmentReadTaskTest.FetchPages_Tiny_InMem
https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-ghpr-unit-tests/runs/13314/log/?start=0
Seems blocked

**Pull request merged**
