### PR TITLE
Enable LTO in release build process

### PR DESCRIPTION
**Pull request by solotzg**
### What problem does this PR solve?

Issue Number: ref #4909 after #4890

Problem Summary:

### What is changed and how it works?

- new feature flag `thinlto` in `./tiflash version`.
- clean useless modules: reduce binary size from 329M to 293M.
- inline function invoke automatically.

----

#### Benchmark

- use cgroup to limit cpu usage to 500% at most.
```
mkdir -p /sys/fs/cgroup/cpu/tzg_test
lsof -i:9000 | grep 'TiFlash' | grep -v 'grep' | awk '{print $2}' > /sys/fs/cgroup/cpu/tzg_test/cgroup.procs
echo "500000" > /sys/fs/cgroup/cpu/tzg_test/cpu.cfs_quota_us
```

```
MySQL [tpch_10]> desc lineitem;
+-----------------+---------------+------+------+---------+-------+
| Field           | Type          | Null | Key  | Default | Extra |
+-----------------+---------------+------+------+---------+-------+
| L_ORDERKEY      | bigint(20)    | NO   | PRI  | NULL    |       |
| L_PARTKEY       | bigint(20)    | NO   |      | NULL    |       |
| L_SUPPKEY       | bigint(20)    | NO   |      | NULL    |       |
| L_LINENUMBER    | bigint(20)    | NO   | PRI  | NULL    |       |
| L_QUANTITY      | decimal(15,2) | NO   |      | NULL    |       |
| L_EXTENDEDPRICE | decimal(15,2) | NO   |      | NULL    |       |
| L_DISCOUNT      | decimal(15,2) | NO   |      | NULL    |       |
| L_TAX           | decimal(15,2) | NO   |      | NULL    |       |
| L_RETURNFLAG    | char(1)       | NO   |      | NULL    |       |
| L_LINESTATUS    | char(1)       | NO   |      | NULL    |       |
| L_SHIPDATE      | date          | NO   |      | NULL    |       |
| L_COMMITDATE    | date          | NO   |      | NULL    |       |
| L_RECEIPTDATE   | date          | NO   |      | NULL    |       |
| L_SHIPINSTRUCT  | char(25)      | NO   |      | NULL    |       |
| L_SHIPMODE      | char(10)      | NO   |      | NULL    |       |
| L_COMMENT       | varchar(44)   | NO   |      | NULL    |       |
+-----------------+---------------+------+------+---------+-------+
16 rows in set (0.00 sec)
```

- run `tpch-10-q1`

| | LTO | original |
| ------ | ------ | ------ |
| AVG Time Cost(s) | 6.042 | 6.322 |

improve 4.63%

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Test release build under x86 and arm64
```
docker run --rm -it -m 40G -v `pwd`:/home/jenkins/agent/workspace/tiflash-build-common/tiflash hub.pingcap.net/tiflash/tiflash-llvm-base:amd64 sh
sh-4.2# NPROC=12 /home/jenkins/agent/workspace/tiflash-build-common/tiflash/release-centos7-llvm/scripts/build-release.sh
```

```
sh-4.2# ./tiflash version
TiFlash
Release Version: v6.1.0-alpha-186-g7eb89fa-dirty
Edition:         Community
Git Commit Hash: 7eb89fac9cc36b789fb0aaf449ac95e1b5897de2
Git Branch:      lto
UTC Build Time:  2022-05-18 09:43:31
Enable Features: jemalloc avx avx512 unwind thinlto
Profile:         RELWITHDEBINFO
...
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by SchrodingerZhu — APPROVED** [review]

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Comment by zanmato1984** [comment]
But I suggest merging this PR after code freeze for 6.1. Leave the uncertainty behind it.

**Pull request merged**
