### PR TITLE
storage: Fix GC for logical split not working

### PR DESCRIPTION
**Pull request by breezewish**
### What problem does this PR solve?

Issue Number: ref #5237

I discovered that some space is not reclaimed after ingestBySplit. After investigation the problem is we are not triggering GC for these segments due to some refactoring mistake introduced in https://github.com/pingcap/tiflash/pull/5863

### What is changed and how it works?

1. Fixed such GC not working

image

2. Changed `merge` in metrics to be `merge_bg_gc` so that it is more clear

3. Made GC logs more verbose

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

Space can be successfully reclaimed after using the new TiFlash binary:

image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

This is a bug fix, however the bug is not release to user so there is no release note.

```release-note
None
```

### CODE REVIEW

**Review by lidezhu — APPROVED** [review]
LGTM

**Review by JaySon-Huang — APPROVED** [review]
lgtm

**Comment by breezewish** [comment]
I guess there are some problems in the master branch:

```
[2022-09-17T13:54:09.190Z]   Error: use test; set @@tidb_isolation_read_engines='tiflash'; select count(distinct pk), count(id), count(value), count(1) from a;
[2022-09-17T13:54:09.190Z]   Result:
[2022-09-17T13:54:09.190Z]     ERROR 1105 (HY000) at line 1: other error for mpp stream: From MPP<query:436056319140823047,task:2>: Code: 0, e.displayText() = DB::TiFlashException: Different aggregation mode detected, e.what() = DB::TiFlashException,
[2022-09-17T13:54:09.190Z]   Expected:
[2022-09-17T13:54:09.190Z]     +--------------------+-----------+--------------+----------+
[2022-09-17T13:54:09.190Z]     | count(distinct pk) | count(id) | count(value) | count(1) |
[2022-09-17T13:54:09.190Z]     +--------------------+-----------+--------------+----------+
[2022-09-17T13:54:09.190Z]     |                  0 |         0 |            0 |        0 |
[2022-09-17T13:54:09.190Z]     +--------------------+-----------+--------------+----------+
```

**Pull request merged**
