### PR TITLE
Unify the url of submodule to https url

### LINKED ISSUE #4565: Unify the url of submodule to https url
## Enhancement
The git clone protocol of some submodule is ssh,  unify the url of submodule to https url.
```
[submodule "contrib/client-c"]
	path = contrib/client-c
	url = git@github.com:tikv/client-c.git
[submodule "contrib/tiflash-proxy"]
	path = contrib/tiflash-proxy
	url = git@github.com:pingcap/tidb-engine-ext.git
[submodule "contrib/prometheus-cpp"]
	path = contrib/prometheus-cpp
	url = git@github.com:jupp0r/prometheus-cpp.git
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #4565

related https://github.com/pingcap/tiflash/pull/4566, https://github.com/pingcap/tiflash/pull/6828

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
And also unify with ".git" or not?

**Review by Lloyd-Pottiger — APPROVED** [review]
Others LGTM

**Review by JaySon-Huang — APPROVED** [review]

**Comment by SeaRise** [comment]
> And also unify with ".git" or not?

ok, updated.

**Pull request merged**
