### PR TITLE
Server: reduce too many pings

### LINKED ISSUE #5688: Got too many pings from the client, closing the connection in TiDB server log files
## Bug Report

Please answer these questions before submitting your issue. Thanks!

See https://github.com/pingcap/tidb/issues/36861 for more details.

### PR DESCRIPTION
**Pull request by jackysp**
Signed-off-by: Jack Yu <jackysp@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/36861
Issue Number: close #5688

Problem Summary:
https://github.com/pingcap/tidb/pull/17885 reduced parts of this kind of logs, it could still be found in v6.1.0. According to https://github.com/grpc/grpc/issues/28830, it seems it is not fixed yet. So disable the external pings for tiflash.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @zanmato1984

**Comment by windtalker** [comment]
Reopen it since client-go disable `PermitWithoutStream` in https://github.com/tikv/client-go/pull/574

**Review by yibin87 — APPROVED** [review]
LGTM

**Pull request merged**
