### PR TITLE
feat: add ifunc dispatch and use it to rewrite deserializeBinary

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Signed-off-by: SchrodingerZhu <i@zhuyi.fan>

### What problem does this PR solve?

Issue Number: ref #5250

see linked issue for details.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by flowbehappy** [comment]
It looks great! Can you provide some metrics about optimization results? @SchrodingerZhu

**Comment by SchrodingerZhu** [comment]
On `Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz`

```
test-x86-64-v2-noopt
benchmarking for strings with average length: 8, cycle count: 1215378
benchmarking for strings with average length: 16, cycle count: 1347574
benchmarking for strings with average length: 32, cycle count: 1502846
benchmarking for strings with average length: 64, cycle count: 2077836
benchmarking for strings with average length: 128, cycle count: 4300778
benchmarking for strings with average length: 256, cycle count: 8418640
benchmarking for strings with average length: 512, cycle count: 18423154
benchmarking for strings with average length: 1024, cycle count: 39344146
benchmarking for strings with average length: 2048, cycle count: 80157570
benchmarking for strings with average length: 4096, cycle count: 161841194
benchmarking for strings with average length: 16384, cycle count: 686186826
test-x86-64-v2-opt
benchmarking for strings with average length: 8, cycle count: 1112418
benchmarking for strings with average length: 16, cycle count: 1176106
benchmarking for strings with average length: 32, cycle count: 1231930
benchmarking for strings with average length: 64, cycle count: 1924574
benchmarking for strings with average length: 128, cycle count: 4222988
benchmarking for strings with average length: 256, cycle count: 8125118
benchmarking for strings with average length: 512, cycle count: 18544760
benchmarking for strings with average length: 1024, cycle count: 38007704
benchmarking for strings with average length: 2048, cycle count: 77796496
benchmarking for strings with average length: 4096, cycle count: 151665098
benchmarking for strings with average length: 16384, cycle count: 684249476
test-x86-64-v2-opt-erms
benchmarking for strings with average length: 8, cycle count: 1186492
benchmarking for strings with average length: 16, cycle count: 1229294
benchmarking for strings with average length: 32, cycle count: 1214910
benchmarking for strings with average length: 64, cycle count: 2082256
benchmarking for strings with average length: 128, cycle count: 4181758
benchmarking for strings with average length: 256, cycle count: 8188724
benchmarking for strings with average length: 512, cycle count: 18387636
benchmarking for strings with average length: 1024, cycle count: 37817384
benchmarking for strings with average length: 2048, cycle count: 79487222
benchmarking for strings with average length: 4096, cycle count: 151686206
benchmarking for strings with average length: 16384, cycle count: 658401156
test-x86-64-v3-noopt
benchmarking for strings with average length: 8, cycle count: 1275308
benchmarking for strings with average length: 16, cycle count: 1371422
benchmarking for strings with average length: 32, cycle count: 1452238
benchmarking for strings with average length: 64, cycle count: 2264058
benchmarking for strings with average length: 128, cycle count: 4716896
benchmarking for strings with average length: 256, cycle count: 8338506
benchmarking for strings with average length: 512, cycle count: 18269212
benchmarking for strings with average length: 1024, cycle count: 37975026
benchmarking for strings with average length: 2048, cycle count: 77486448
benchmarking for strings with average length: 4096, cycle count: 153178130
benchmarking for strings with average length: 16384, cycle count: 673426300
test-x86-64-v3-opt
benchmarking for strings with average length: 8, cycle count: 1148870
benchmarking for strings with average length: 16, cycle count: 1203526
benchmarking for strings with average length: 32, cycle count: 1310552
benchmarking for strings with average length: 64, cycle count: 2111892
benchmarking for strings with average length: 128, cycle count: 4322316
benchmarking for strings with average length: 256, cycle count: 7790968
benchmarking for strings with average length: 512, cycle count: 17708700
benchmarking for strings with average length: 1024, cycle count: 36808382
benchmarking for strings with average length: 2048, cycle count: 76788562
benchmarking for strings with average length: 4096, cycle count: 151606294
benchmarking for strings with average length: 16384, cycle count: 648925730
test-x86-64-v3-opt-erms
benchmarking for strings with average length: 8, cycle count: 1082758
benchmarking for strings with average length: 16, cycle count: 1193634
benchmarking for strings with average length: 32, cycle count: 1228206
benchmarking for strings with average length: 64, cycle count: 2255824
benchmarking for strings with average length: 128, cycle count: 5178236
benchmarking for strings with average length: 256, cycle count: 8689460
benchmarking for strings with average length: 512, cycle count: 16490080
benchmarking for strings with average length: 1024, cycle count: 36136658
benchmarking for strings with average length: 2048, cycle count: 75306590
benchmarking for strings with average length: 4096, cycle count: 160397656
benchmarking for strings with average length: 16384, cycle count: 663662406
test-x86-64-v4-noopt
benchmarking for strings with average length: 8, cycle count: 1242722
benchmarking for strings with average length: 16, cycle count: 1351408
benchmarking for strings with average length: 32, cycle count: 1372044
benchmarking for strings with average length: 64, cycle count: 2383004
benchmarking for strings with average length: 128, cycle count: 4473374
benchmarking for strings with average length: 256, cycle count: 7751108
benchmarking for strings with average length: 512, cycle count: 17182022
benchmarking for strings with average length: 1024, cycle count: 36190984
benchmarking for strings with average length: 2048, cycle count: 76888166
benchmarking for strings with average length: 4096, cycle count: 161321770
benchmarking for strings with average length: 16384, cycle count: 643219610
test-x86-64-v4-opt
benchmarking for strings with average length: 8, cycle count: 1173618
benchmarking for strings with average length: 16, cycle count: 1208468
benchmarking for strings with average length: 32, cycle count: 1563332
benchmarking for strings with average length: 64, cycle count: 2095068
benchmarking for strings with average length: 128, cycle count: 4322508
benchmarking for strings with average length: 256, cycle count: 7793832
benchmarking for strings with average length: 512, cycle count: 17239122
benchmarking for strings with average length: 1024, cycle count: 36986224
benchmarking for strings with average length: 2048, cycle count: 73021128
benchmarking for strings with average length: 4096, cycle count: 150188206
benchmarking for strings with average length: 16384, cycle count: 643174656
test-x86-64-v4-opt-erms
benchmarking for strings with average length: 8, cycle count: 1140942
benchmarking for strings with average length: 16, cycle count: 1200774
benchmarking for strings with average length: 32, cycle count: 1314276
benchmarking for strings with average length: 64, cycle count: 2020584
benchmarking for strings with average length: 128, cycle count: 4301806
benchmarking for strings with average length: 256, cycle count: 7686334
benchmarking for strings with average length: 512, cycle count: 16954712
benchmarking for strings with average length: 1024, cycle count: 35553576
benchmarking for strings with average length: 2048, cycle count: 72725060
benchmarking for strings with average length: 4096, cycle count: 148433888
benchmarking for strings with average length: 16384, cycle count: 631375740

```

**Comment by SchrodingerZhu** [comment]
On `AMD Ryzen 9 3950X 16-Core Processor`
```
test-x86-64-v2-noopt
benchmarking for strings with average length: 8, cycle count: 856100
benchmarking for strings with average length: 16, cycle count: 879270
benchmarking for strings with average length: 32, cycle count: 836080
benchmarking for strings with average length: 64, cycle count: 1271025
benchmarking for strings with average length: 128, cycle count: 2032660
benchmarking for strings with average length: 256, cycle count: 4470200
benchmarking for strings with average length: 512, cycle count: 8990450
benchmarking for strings with average length: 1024, cycle count: 19998195
benchmarking for strings with average length: 2048, cycle count: 43333710
benchmarking for strings with average length: 4096, cycle count: 92043525
benchmarking for strings with average length: 16384, cycle count: 404961130
test-x86-64-v2-opt
benchmarking for strings with average length: 8, cycle count: 744905
benchmarking for strings with average length: 16, cycle count: 831075
benchmarking for strings with average length: 32, cycle count: 773045
benchmarking for strings with average length: 64, cycle count: 1186675
benchmarking for strings with average length: 128, cycle count: 2031260
benchmarking for strings with average length: 256, cycle count: 6384560
benchmarking for strings with average length: 512, cycle count: 12451180
benchmarking for strings with average length: 1024, cycle count: 26642770
benchmarking for strings with average length: 2048, cycle count: 56815150
benchmarking for strings with average length: 4096, cycle count: 114407790
benchmarking for strings with average length: 16384, cycle count: 497240695
test-x86-64-v2-opt-erms
benchmarking for strings with average length: 8, cycle count: 740565
benchmarking for strings with average length: 16, cycle count: 826385
benchmarking for strings with average length: 32, cycle count: 766500
benchmarking for strings with average length: 64, cycle count: 1203685
benchmarking for strings with average length: 128, cycle count: 2022965
benchmarking for strings with average length: 256, cycle count: 6209875
benchmarking for strings with average length: 512, cycle count: 12318285
benchmarking for strings with average length: 1024, cycle count: 24674300
benchmarking for strings with average length: 2048, cycle count: 50678845
benchmarking for strings with average length: 4096, cycle count: 103217590
benchmarking for strings with average length: 16384, cycle count: 454437865
test-x86-64-v3-noopt
benchmarking for strings with average length: 8, cycle count: 792540
benchmarking for strings with average length: 16, cycle count: 834120
benchmarking for strings with average length: 32, cycle count: 812035
benchmarking for strings with average length: 64, cycle count: 1261820
benchmarking for strings with average length: 128, cycle count: 1960210
benchmarking for strings with average length: 256, cycle count: 4882745
benchmarking for strings with average length: 512, cycle count: 8660085
benchmarking for strings with average length: 1024, cycle count: 20420820
benchmarking for strings with average length: 2048, cycle count: 43021930
benchmarking for strings with average length: 4096, cycle count: 89887420
benchmarking for strings with average length: 16384, cycle count: 403419835
test-x86-64-v3-opt
benchmarking for strings with average length: 8, cycle count: 744730
benchmarking for strings with average length: 16, cycle count: 813575
benchmarking for strings with average length: 32, cycle count: 774620
benchmarking for strings with average length: 64, cycle count: 1170820
benchmarking for strings with average length: 128, cycle count: 1930670
benchmarking for strings with average length: 256, cycle count: 4313015
benchmarking for strings with average length: 512, cycle count: 8830815
benchmarking for strings with average length: 1024, cycle count: 20423480
benchmarking for strings with average length: 2048, cycle count: 44200310
benchmarking for strings with average length: 4096, cycle count: 90866545
benchmarking for strings with average length: 16384, cycle count: 402334380
test-x86-64-v3-opt-erms
benchmarking for strings with average length: 8, cycle count: 726110
benchmarking for strings with average length: 16, cycle count: 808290
benchmarking for strings with average length: 32, cycle count: 777945
benchmarking for strings with average length: 64, cycle count: 1198225
benchmarking for strings with average length: 128, cycle count: 1964235
benchmarking for strings with average length: 256, cycle count: 4822300
benchmarking for strings with average length: 512, cycle count: 9016840
benchmarking for strings with average length: 1024, cycle count: 23135735
benchmarking for strings with average length: 2048, cycle count: 49846195
benchmarking for strings with average length: 4096, cycle count: 103121830
benchmarking for strings with average length: 16384, cycle count: 455732270
test-x86-64-v4-noopt
benchmarking for strings with average length: 8, test.sh: line 14: 522966 Illegal instruction     (core dumped) ./test-x86-64-$i-$j
test-x86-64-v4-opt
benchmarking for strings with average length: 8, test.sh: line 14: 522975 Illegal instruction     (core dumped) ./test-x86-64-$i-$j
test-x86-64-v4-opt-erms
benchmarking for strings with average length: 8, test.sh: line 14: 522985 Illegal instruction     (core dumped) ./test-x86-64-$i-$j
iin
```

**Comment by SchrodingerZhu** [comment]
On `aarch64`:
```
noopt
benchmarking for strings with average length: 8, time count: 597177
benchmarking for strings with average length: 16, time count: 695688
benchmarking for strings with average length: 32, time count: 844380
benchmarking for strings with average length: 64, time count: 1084893
benchmarking for strings with average length: 128, time count: 1518689
benchmarking for strings with average length: 256, time count: 2161396
benchmarking for strings with average length: 512, time count: 4261451
benchmarking for strings with average length: 1024, time count: 8281748
benchmarking for strings with average length: 2048, time count: 17572470
benchmarking for strings with average length: 4096, time count: 32396637
benchmarking for strings with average length: 16384, time count: 122472002
opt
benchmarking for strings with average length: 8, time count: 448725
benchmarking for strings with average length: 16, time count: 504546
benchmarking for strings with average length: 32, time count: 586517
benchmarking for strings with average length: 64, time count: 788909
benchmarking for strings with average length: 128, time count: 1155193
benchmarking for strings with average length: 256, time count: 1739600
benchmarking for strings with average length: 512, time count: 3289289
benchmarking for strings with average length: 1024, time count: 7836974
benchmarking for strings with average length: 2048, time count: 15356923
benchmarking for strings with average length: 4096, time count: 29793675
benchmarking for strings with average length: 16384, time count: 118897298

```

**Comment by SchrodingerZhu** [comment]
AMD:
test scripts:
```
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v2-noopt -march=x86-64-v2
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v3-noopt -march=x86-64-v3
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v4-noopt -march=x86-64-v4

clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v2-opt -march=x86-64-v2 -DOPTIMISTIC_BRANCH
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v3-opt -march=x86-64-v3 -DOPTIMISTIC_BRANCH
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v4-opt -march=x86-64-v4 -DOPTIMISTIC_BRANCH

clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v2-opt-erms -march=x86-64-v2 -DOPTIMISTIC_BRANCH -DERMS
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v3-opt-erms -march=x86-64-v3 -DOPTIMISTIC_BRANCH -DERMS
clang++ -O3 -std=c++17 -g3 test.cc -o test-x86-64-v4-opt-erms -march=x86-64-v4 -DOPTIMISTIC_BRANCH -DERMS

for i in v2 v3 v4; do
        for j in noopt opt opt-erms; do
                echo test-x86-64-$i-$j
                ./test-x86-64-$i-$j
        done
done
```
ARM
```
clang++ -O3 -std=c++17 -g3 test.cc -o test-noopt
clang++ -O3 -std=c++17 -g3 test.cc -o test-opt -DOPTIMISTIC_BRANCH

echo noopt; ./test-noopt
echo opt; ./test-opt

```

**Comment by flowbehappy** [comment]
Nice. And can you make a conclusion of those benchmark results? @SchrodingerZhu

**Comment by SchrodingerZhu** [comment]
@flowbehappy generally, the shorter the faster. 

For x86, 
- Within `x86-64-v*`, we can see that optimistic routines can generally improve the performance, and erms can indeed improve the performance.
- Across  `x86-64-v*`, we can see that wider register can provide potentially more speedup.
For aarch64,
previous implementations does not have optimistic routine, and current implementation enables it. On Kunpeng processor, we can directly see that the optimistic routine wins an edge.

**Pull request closed without merging**
