### PR TITLE
build: fix benchmark compile

### LINKED ISSUE #6721: Compile bench fail

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #6721 

Problem Summary:

### What is changed and how it works?

remove outdated microbenchmark, too many errors...

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by ywqzzy** [comment]
No, we need bench_exchange!!

**Comment by ywqzzy** [comment]
> No, we need bench_exchange and bench_window!!

**Comment by Lloyd-Pottiger** [comment]
> No, we need bench_exchange and bench_window!!

rebasing.

**Comment by Lloyd-Pottiger** [comment]
> No, we need bench_exchange and bench_window!!

still fail to fix, please fix them if we really need them

**Pull request closed without merging**
