### PR TITLE
[DNM] Add the read node role for TiFlash

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary: A feature branch for adding the read node role for TiFlash

### What is changed and how it works?

- Enable config engine-label for tiflash_proxy, check etc/config-template.toml

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by guo-shaoge** [comment]
Maybe we should add a check to ensure that tiflash ReadNode will not store any region data. Otherwise will give error or something. @JaySon-Huang

**Comment by JaySon-Huang** [comment]
> Maybe we should add a check to ensure that tiflash ReadNode will not store any region data. Otherwise will give error or something. @JaySon-Huang

We can add some checks in KVStore's Region related function for read node

**Comment by JaySon-Huang** [comment]
done by https://github.com/pingcap/tiflash/pull/6248

**Pull request closed without merging**
