### PR TITLE
fix daily fail

### LINKED ISSUE #7881: TiFlash daily test fails
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```

[2023-08-01T14:24:41.752Z] ---------------------

[2023-08-01T14:24:43.117Z] [0] {PARALLEL_MARK:RUN} "tpch/load" "0.1" "lineitem" "true" "4" "" "decimal" "/home/jenkins/agent/git/tiflash/integrated/data/tpch" "3" ":" "wait/available" "tpch_0_1" "lineitem" ":" "sleep" "120"

[2023-08-01T14:24:43.117Z] [1] {PARALLEL_MARK:RUN} "wait/available" "tpch_0_1" "lineitem" LOOP: "verify/consistency" "tpch_0_1" "lineitem"

[2023-08-01T14:24:48.362Z] [0] =====================

[2023-08-01T14:24:48.362Z] [0] :: tpch/load "0.1" "lineitem" "true" "4" "" "decimal" "/home/jenkins/agent/git/tiflash/integrated/data/tpch" "3"

[2023-08-01T14:24:48.362Z] [0] ---------------------

[2023-08-01T14:24:48.362Z] [0] => [127.0.0.1] creating tpch_0_1.lineitem

[2023-08-01T14:24:48.362Z] [0] => [127.0.0.1] loading tpch_0_1.lineitem

[2023-08-01T14:24:48.362Z] [1] => wait for tpch_0_1.lineitem available in tiflash

[2023-08-01T14:24:53.613Z] [0]    generated

[2023-08-01T14:24:53.613Z] [0]    tpch_0_1.lineitem: tikv -> tiflash

[2023-08-01T14:24:53.613Z] [1]    available

[2023-08-01T14:24:53.613Z] [1] {PARALLEL_MARK:HALF_DONE}

[2023-08-01T14:24:58.856Z] [1] Received exception from server (version 1.1.54381):

[2023-08-01T14:24:58.856Z] [1] Code: 81. DB::Exception: Received from 127.0.0.1:4992. DB::Exception: in mappedDatabase, Database tpch_0_1 not found. 
```

### PR DESCRIPTION
**Pull request by windtalker**
### What problem does this PR solve?

Issue Number: close #7881

Problem Summary:
The root cause is the retry logical in our daily test rely on the output format of some error message.
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

**Review by hongyunyan — APPROVED** [review]
LGTM

**Comment by SeaRise** [comment]
ci fail because of https://github.com/pingcap/tiflash/issues/7884

**Comment by SeaRise** [comment]
> ci fail because of #7884

fixed

**Pull request merged**
