### PR TITLE
fix memory leaks in *.ListBase 

### LINKED ISSUE #5769: LeakSanitizer: detected memory leaks in *.ListBase
## Enhancement
```
[2022-09-01T19:22:08.275Z] FAILED TESTS (3/1492):
[2022-09-01T19:22:08.275Z]     2358 ms: /tiflash/gtests_dbms InterpreterExecuteTest.ListBase
[2022-09-01T19:22:08.275Z]     2991 ms: /tiflash/gtests_dbms PlannerInterpreterExecuteTest.ListBase
[2022-09-01T19:22:08.275Z]     2376 ms: /tiflash/gtests_dbms MockDAGRequestTest.ListBase
```
```
[2022-09-01T19:17:21.435Z] Direct leak of 168 byte(s) in 1 object(s) allocated from:
[2022-09-01T19:17:21.435Z]     #0 0x3826d0d in operator new(unsigned long) /llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
[2022-09-01T19:17:21.435Z]     #1 0x19be2932 in google::protobuf::Arena::InternalHelper<tipb::Executor>::New() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/protobuf/src/google/protobuf/arena.h:494:14
[2022-09-01T19:17:21.435Z]     #2 0x19be2932 in tipb::Executor* google::protobuf::Arena::CreateMessageInternal<tipb::Executor>(google::protobuf::Arena*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/protobuf/src/google/protobuf/arena.h:559:14
[2022-09-01T19:17:21.435Z]     #3 0x19be2932 in tipb::Executor* google::protobuf::Arena::CreateMaybeMessage<tipb::Executor>(google::protobuf::Arena*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/build-ASan/contrib/tipb/cpp/tipb/executor.pb.cc:7715:10
[2022-09-01T19:17:21.435Z]     #4 0x87e7085 in tipb::Executor* google::protobuf::MessageLite::CreateMaybeMessage<tipb::Executor>(google::protobuf::Arena*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/protobuf/src/google/protobuf/message_lite.h:428:12
[2022-09-01T19:17:21.435Z]     #5 0x87e7085 in tipb::DAGRequest::_internal_mutable_root_executor() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/build-ASan/contrib/tipb/cpp/tipb/select.pb.h:3723:15
[2022-09-01T19:17:21.435Z]     #6 0x87e7085 in tipb::DAGRequest::mutable_root_executor() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/build-ASan/contrib/tipb/cpp/tipb/select.pb.h:3729:28
[2022-09-01T19:17:21.435Z]     #7 0x87e7085 in DB::tests::DAGRequestBuilder::build(DB::tests::MockDAGRequestContext&, DB::tests::DAGRequestType) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/mockExecutor.cpp:95:38
[2022-09-01T19:17:21.435Z]     #8 0x3ea4706 in DB::tests::InterpreterExecuteTest_ListBase_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/tests/gtest_interpreter.cpp:661:29
[2022-09-01T19:17:21.436Z]     #9 0x148f88d0 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2022-09-01T19:17:21.436Z]     #10 0x148f88d0 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2022-09-01T19:17:21.436Z]     #11 0x14897078 in testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5
[2022-09-01T19:17:21.436Z]     #12 0x1489a207 in testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11
[2022-09-01T19:17:21.436Z]     #13 0x1489b77f in testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28
[2022-09-01T19:17:21.436Z]     #14 0x148c6198 in testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43
[2022-09-01T19:17:21.436Z]     #15 0x148faed0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10
[2022-09-01T19:17:21.436Z]     #16 0x148faed0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14
[2022-09-01T19:17:21.436Z]     #17 0x148c4a11 in testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10
[2022-09-01T19:17:21.436Z]     #18 0x84fb9aa in RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46
[2022-09-01T19:17:21.436Z]     #19 0x84fb9aa in main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:78:16
[2022-09-01T19:17:21.436Z]     #20 0x7f6fe0c98554 in __libc_start_main (/lib64/libc.so.6+0x22554)
[2022-09-01T19:17:21.436Z] 
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #5769

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
> /run-sanitizer-test asan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-sanitizer/detail/tiflash-ghpr-sanitizer/36/pipeline

**Comment by SeaRise** [comment]
> > /run-sanitizer-test asan
> 
> https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-sanitizer/detail/tiflash-ghpr-sanitizer/36/pipeline

passed.

**Review by ywqzzy — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]

**Pull request merged**
