### PR TITLE
ci: upgrade tiflash-ci-base image to use rocky linux8

### PR DESCRIPTION
**Pull request by purelind**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/9562

Problem Summary: upgrade ci base image from centos7 to rocky linux 8 because centos7 end of life.

### What is changed and how it works?

```commit-message
* update base image to rocky linux 8
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by purelind** [comment]
Another related PR needs to be merged first: https://github.com/PingCAP-QE/ci/pull/3186

**Review by Lloyd-Pottiger — APPROVED** [review]
lgtm

**Review by gengliqi — APPROVED** [review]

**Pull request merged**
