### PR TITLE
tests: remove raftstore-v2 integration test

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #6233

Problem Summary:

### What is changed and how it works?

tasks a long time, but has no meaning now, so just remove.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CalvinNeo — COMMENTED** [review]
Do we also remove `tests/docker/cluster-v2.yaml`?

**Comment by Lloyd-Pottiger** [comment]
> Do we also remove `tests/docker/cluster-v2.yaml`?

Now we just comment out the test, should we completely remove it?

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Pull request merged**
