### PR TITLE
Tsan: fix data race in `MPPTunnel::updateConnProfileInfo`

### LINKED ISSUE #6959: Tsan: data race in `MPPTunnel::updateConnProfileInfo`
`updateConnProfileInfo` should be locked or atomic variables should be used.
```
  Read of size 8 at 0x7b480002c7e0 by thread T603:
[2023-03-05T18:06:58.405Z]     #0 DB::MPPTunnel::updateConnProfileInfo(unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Mpp/MPPTunnel.h:553:41 (gtests_dbms+0xd3c25e4)
[2023-03-05T18:06:58.405Z]     #1 DB::MPPTunnel::write(std::__1::shared_ptr<DB::TrackedMppDataPacket>&&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Mpp/MPPTunnel.cpp:172:9 (gtests_dbms+0xd3c25e4)
[2023-03-05T18:06:58.405Z]     #2 DB::MPPTunnelSetBase<DB::MPPTunnel>::write(tipb::SelectResponse&, unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Mpp/MPPTunnelSet.cpp:60:21 (gtests_dbms+0xd3d72c8)
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #6959

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/932/pipeline

**Review by ywqzzy — APPROVED** [review]

**Review by LittleFall — APPROVED** [review]

**Pull request merged**
