### PR TITLE
*: Fix verbose logging in the DeltaTree engine

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/5718

Problem Summary:

After https://github.com/pingcap/tiflash/pull/5715, the logging become too verbose for mpp task, the tso appear many times
```
[2022/09/06 17:05:28.830 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=146 epoch=17> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=89]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=1 epoch=32> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=90]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=146 epoch=17> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=91]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1485] ["Segment:<segment_id=1 epoch=32> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Finish segment getReadInfo"] [thread_id=90]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=149 epoch=14> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=92]
[2022/09/06 17:05:28.831 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=149 epoch=14> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=93]
[2022/09/06 17:05:28.832 +08:00] [DEBUG] [Segment.cpp:1485] ["Segment:<segment_id=149 epoch=14> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Finish segment getReadInfo"] [thread_id=92]
[2022/09/06 17:05:28.832 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=146 epoch=17> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=94]
[2022/09/06 17:05:28.832 +08:00] [DEBUG] [Segment.cpp:1485] ["Segment:<segment_id=149 epoch=14> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Finish segment getReadInfo"] [thread_id=93]
[2022/09/06 17:05:28.832 +08:00] [DEBUG] [Segment.cpp:1470] ["Segment:<segment_id=152 epoch=14> MPP<query:435802637197639681,task:1> Table<129> read_tso=435802637197639681 Begin segment getReadInfo"] [thread_id=95]
```

### What is changed and how it works?

* Use the tso in mpp prefix `MPP<query:435802637197639681,task:1>` for running rough set test
* Make rough set tests run queries under mpp
* Remove the `read_tso=xxx` from logging

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
Something wrong between tikv and pd connection
```
[2022-09-07T09:43:54.860Z]   File: fullstack-test2/auto_gen/basic_codec.test
[2022-09-07T09:43:54.860Z]   Error line: 33
[2022-09-07T09:43:54.860Z]   Error: wait_table test t
[2022-09-07T09:43:54.860Z]   Result:
[2022-09-07T09:43:54.860Z]     => wait for test.t available in TiFlash
[2022-09-07T09:43:54.861Z]     => cannot sync tables in 600.021801949s
```

**Review by lidezhu — APPROVED** [review]
LGTM

**Pull request merged**
