### PR TITLE
Fix new segment check in gcTrySegmentMergeDelta/gcTrySegmentMerge

### LINKED ISSUE #6775: gcTrySegmentMergeDelta/gcTrySegmentMerge don't check the expected segments
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

we check the expected segments in gcTrySegmentMergeDelta/gcTrySegmentMerge.

### 3. What did you see instead (Required)

we check the abondoned segments in gcTrySegmentMergeDelta/gcTrySegmentMerge.

### 4. What is your TiFlash version? (Required)

nightly

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close #6775

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
so some checks are not apply to the expected segments🤣
I think we'd better create a standalone issue for it and cherry it back to the LTS versions

**Comment by hongyunyan** [comment]
> so some checks are not apply to the expected segments🤣 I think we'd better create a standalone issue for it so that cherry it back to the LTS versions

OK, I will create a standalone issue.

**Review by JaySon-Huang — APPROVED** [review]
lgtm

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
