### PR TITLE
Fix exception thrown when reading from multiple partitions under S3 disagg

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/7187, ref https://github.com/pingcap/tiflash/issues/6827

Problem Summary:

<details>
    <summary> build a partition table and analyze it </summary>

```
# insert some rows to 
SET @@sql_mode = '';

CREATE TABLE employees  (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(25) NOT NULL,
    lname VARCHAR(25) NOT NULL,
    store_id INT NOT NULL,
    department_id INT NOT NULL
)

PARTITION BY RANGE(id)  (
    PARTITION p0 VALUES LESS THAN (5),
    PARTITION p1 VALUES LESS THAN (10),
    PARTITION p2 VALUES LESS THAN (15),
    PARTITION p3 VALUES LESS THAN MAXVALUE
);

INSERT INTO employees VALUES
    ('', 'Bob', 'Taylor', 3, 2), ('', 'Frank', 'Williams', 1, 2),
    ('', 'Ellen', 'Johnson', 3, 4), ('', 'Jim', 'Smith', 2, 4),
    ('', 'Mary', 'Jones', 1, 1), ('', 'Linda', 'Black', 2, 3),
    ('', 'Ed', 'Jones', 2, 1), ('', 'June', 'Wilson', 3, 1),
    ('', 'Andy', 'Smith', 1, 3), ('', 'Lou', 'Waters', 2, 4),
    ('', 'Jill', 'Stone', 1, 4), ('', 'Roger', 'White', 3, 2),
    ('', 'Howard', 'Andrews', 1, 2), ('', 'Fred', 'Goldberg', 3, 3),
    ('', 'Barbara', 'Brown', 2, 3), ('', 'Alice', 'Rogers', 2, 2),
    ('', 'Mark', 'Morgan', 3, 3), ('', 'Karen', 'Cole', 3, 2);

analyze table employees;

explain select * from employees;
+---------------------+---------+--------------+-----------------+-------------------------------------------+
| id                  | estRows | task         | access object   | operator info                             |
+---------------------+---------+--------------+-----------------+-------------------------------------------+
| TableReader_10      | 18.00   | root         | partition:all   | MppVersion: 1, data:ExchangeSender_9      |
| └─ExchangeSender_9  | 18.00   | mpp[tiflash] |                 | ExchangeType: PassThrough                 |
|   └─TableFullScan_8 | 18.00   | mpp[tiflash] | table:employees | keep order:false, PartitionTableScan:true |
+---------------------+---------+--------------+-----------------+-------------------------------------------+
```

</details>

* When reading rows from multiple partitions, and [`dynamic puring`](https://docs.pingcap.com/tidb/dev/partitioned-table#dynamic-pruning-mode) is enabled, building disagg tasks with throw error like `DB::Exception: Check res.second failed: Duplicated task from store_id=xxx`
* Lack of `request_id` for locating the problem of S3

### What is changed and how it works?

* Add a new class `RNRemoteStoreReadTask` to represent the store layer read tasks
* Add request_id to the error message generated from S3
* Fix a crash issue when create etcd session failed

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]
Just curious, when reading from partitions, they have different physical table ids, and how does the error comes from?

**Comment by JaySon-Huang** [comment]
> Just curious, when reading from partitions, they have different physical table ids, and how does the error comes from?

The execution plan when dynamic puring is enabled. `PartitionTableScan` contains multiple physical table ids in one MPP task.
```
> explain select * from employees;
+---------------------+---------+--------------+-----------------+-------------------------------------------+
| id                  | estRows | task         | access object   | operator info                             |
+---------------------+---------+--------------+-----------------+-------------------------------------------+
| TableReader_10      | 18.00   | root         | partition:all   | MppVersion: 1, data:ExchangeSender_9      |
| └─ExchangeSender_9  | 18.00   | mpp[tiflash] |                 | ExchangeType: PassThrough                 |
|   └─TableFullScan_8 | 18.00   | mpp[tiflash] | table:employees | keep order:false, PartitionTableScan:true |
+---------------------+---------+--------------+-----------------+-------------------------------------------+
```

The execution plan when dynamic puring is disabled. tidb will file an MPP task for each partition with a `TableScan`, which only contains 1 physical table id.
```
> explain select * from employees;
+------------------------+---------+--------------+-------------------------------+---------------------------------------+
| id                     | estRows | task         | access object                 | operator info                         |
+------------------------+---------+--------------+-------------------------------+---------------------------------------+
| PartitionUnion_10      | 18.00   | root         |                               |                                       |
| ├─TableReader_14       | 4.00    | root         |                               | MppVersion: 1, data:ExchangeSender_13 |
| │ └─ExchangeSender_13  | 4.00    | mpp[tiflash] |                               | ExchangeType: PassThrough             |
| │   └─TableFullScan_12 | 4.00    | mpp[tiflash] | table:employees, partition:p0 | keep order:false, stats:pseudo        |
| ├─TableReader_17       | 5.00    | root         |                               | MppVersion: 1, data:ExchangeSender_16 |
| │ └─ExchangeSender_16  | 5.00    | mpp[tiflash] |                               | ExchangeType: PassThrough             |
| │   └─TableFullScan_15 | 5.00    | mpp[tiflash] | table:employees, partition:p1 | keep order:false, stats:pseudo        |
| ├─TableReader_20       | 5.00    | root         |                               | MppVersion: 1, data:ExchangeSender_19 |
| │ └─ExchangeSender_19  | 5.00    | mpp[tiflash] |                               | ExchangeType: PassThrough             |
| │   └─TableFullScan_18 | 5.00    | mpp[tiflash] | table:employees, partition:p2 | keep order:false, stats:pseudo        |
| └─TableReader_23       | 4.00    | root         |                               | MppVersion: 1, data:ExchangeSender_22 |
|   └─ExchangeSender_22  | 4.00    | mpp[tiflash] |                               | ExchangeType: PassThrough             |
|     └─TableFullScan_21 | 4.00    | mpp[tiflash] | table:employees, partition:p3 | keep order:false, stats:pseudo        |
+------------------------+---------+--------------+-------------------------------+---------------------------------------+
```

1. When dynamic puring is enabled, RN will send a `ParitionTableScan` to WN when `EstablishDisaggTask`. The `PartitionTableScan` contains multiple physical table id and their Regions
2. WN will collect all snapshots from different physical tables and return in on `EstablishDisaggTaskResponse`
3. RN receives the `EstablishDisaggTaskResponse` and parses each physical as `RNRemoteTableReadTask`, so there are multiple `RNRemoteTableReadTask` with the same `store_id` in the `build_results ` https://github.com/pingcap/tiflash/blob/1dc2d1af13e67f8c0b51414329aef71cbc5209ef/dbms/src/Storages/StorageDisaggregatedRemote.cpp#L289-L318
4. When RN tries to build `RNRemoteReadTask` by `build_results`, the check failed and an exception is thrown https://github.com/pingcap/tiflash/blob/1dc2d1af13e67f8c0b51414329aef71cbc5209ef/dbms/src/Storages/DeltaMerge/Remote/RNRemoteReadTask.cpp#L55-L64

**Review by lidezhu — APPROVED** [review]

**Pull request merged**
