### PR TITLE
Storage: add RSOperator batch check

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>

### What problem does this PR solve?

Issue Number: ref #6295

Problem Summary:

### What is changed and how it works?

add RSOperator batch check
- avoid getting rsindex continuously
- batch compute handle_res

TODO:
- To further improve performance, we will let `RSRusult` be a `bool`. 

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hongyunyan** [comment]
Could you please give a microbenchmark result to show the performance gain by batch check?

**Comment by hongyunyan** [comment]
I think maybe L194 in dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h can also use batch check to make optimzation?

**Comment by Lloyd-Pottiger** [comment]
> Could you please give a microbenchmark result to show the performance gain by batch check?

minor changes, so no benchmark. And it is necessary to generate a large number of packs in order to see the implementation, so...

> I think maybe L194 in dbms/src/Storages/DeltaMerge/File/DMFilePackFilter.h can also use batch check to make optimization?

yes, I missed it, I will do that.

**Pull request closed without merging**
