### PR TITLE
Tiflash crash when scanning partition table with `time` column

### LINKED ISSUE #4526: Tiflash crash when scanning partition table with `time` column
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `test`.`test` (
  `COL1` smallint(28) unsigned DEFAULT 0,
  `COL2` time  DEFAULT NULL
)
PARTITION BY RANGE (COL1) (
PARTITION p0 VALUES LESS THAN (2),
PARTITION p3 VALUES LESS THAN MAXVALUE
)
;
ALTER TABLE `test`.`test` SET TIFLASH REPLICA 1;
insert into test.test values
(1, now()),
(2, now()),
(3, now());


set tidb_allow_mpp=1;set tidb_enforce_mpp=1; set tidb_isolation_read_engines='tiflash';
set tidb_partition_prune_mode= dynamic;

select COL2 from test.test;
```

### 2. What did you expect to see? (Required)
query success

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): rpc error: code = Unavailable desc = error reading from server: EOF
tiflash quit: signal: segmentation fault (core dumped)
```

### 4. What is your TiFlash version? (Required)
v6.1.0-alpha-nightly-20220327

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #4526

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
fix tiflash crash when using time column to scan partition table.
```

### CODE REVIEW

**Review by fuzhe1989 — APPROVED** [review]

**Comment by windtalker** [comment]
Add a fullstack test for `time` column?

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
