### PR TITLE
change cpu feature behavior for M1

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>

### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/5368

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Comment by SchrodingerZhu** [comment]
@JaySon-Huang PTAL

**Review by JaySon-Huang — APPROVED** [review]
lgtm

**Pull request merged**
