### PR TITLE
Set status-thread-pool-size to 2 by default

### LINKED ISSUE #6347: Abnormal metrics reported by tiflash-proxy
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deploy a v6.4.0 cluster and run high pressure update workloads.

### 3. What did you see instead (Required)
The CPU and memory reported by tiflash-proxy is abnormal. However, the metrics reported by tiflash is OK
image
image

### 4. What is your TiFlash version? (Required)
v6.4.0

### PR DESCRIPTION
**Pull request by hehechen**
Signed-off-by: hehechen <awd123456sss@gmail.com>

### What problem does this PR solve?

Issue Number: close #6347

Problem Summary:
It seems that the profiling overhead of `dwarf` is larger than that of `frame pointer.` So set `status-thread-pool-size `to 2 by default to avoid the `status_server` thread being stuck and unable to process the http request from prometheus.
### What is changed and how it works?
Set `status-thread-pool-size `to 2 by default to avoid the `status_server` thread being stuck and unable to process the http request from prometheus.
Proxy PR: https://github.com/pingcap/tidb-engine-ext/pull/224
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Enable `continuous profiling`, and then `go-tpc ch --warehouses 1500 -T 100 -t 1 --time 90m  --queries "q1"` and check if the metrics abnormal.
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by JaySon-Huang** [comment]
> It seems that the profiling overhead of `dwarf` is larger than that of `frame pointer`

I think setting `status-thread-pool-size` to 2 is a workaround. Running profiling for 10s but actually cost more than 1 minute still cause other problems. Can we speed up the efficiency of `dwarf` resolving like caching the result?

**Comment by hehechen** [comment]
> > It seems that the profiling overhead of `dwarf` is larger than that of `frame pointer`
> 
> I think setting `status-thread-pool-size` to 2 is a workaround. Running profiling for 10s but actually cost more than 1 minute still cause other problems. Can we speed up the efficiency of `dwarf` resolving like caching the result?

Yes, it's the workaround for v6.5. I will try to speed up the efficiency in the next version.

**Comment by JaySon-Huang** [comment]
> > > It seems that the profiling overhead of `dwarf` is larger than that of `frame pointer`
> > 
> > 
> > I think setting `status-thread-pool-size` to 2 is a workaround. Running profiling for 10s but actually cost more than 1 minute still cause other problems. Can we speed up the efficiency of `dwarf` resolving like caching the result?
> 
> Yes, it's the workaround for v6.5. I will try to speed up the efficiency in the next version.

OK, remember to create an issue for the profiling cost.

**Review by JaySon-Huang — APPROVED** [review]
lgtm as a workaround on v6.5

**Pull request merged**
