### PR TITLE
fix(cmake): make sure libc++ is utilized by tiflash-proxy

### LINKED ISSUE #5282: TiFlash Proxy unexpectedly utilizes `libstdc++`
## Bug Report

origin_img_v2_6d35f783-b963-4f95-bb0d-486ce6dd824g

It has been repeatedly reported that building tiflash in an env where `clang` is not customized to use `libc++` in the first place, `tiflash-proxy` may end up with using `libstdc++` instead, which causes extra trouble and makes it inconsistent with what we are distributing.

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Signed-off-by: Schrodinger ZHU Yifan <i@zhuyi.fan>

### What problem does this PR solve?

Issue Number: close #5282 

Problem Summary:

### What is changed and how it works?

Building TiFlash on Archlinux with system default LLVM toolchain now gives:

image

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by RinChanNOWWW** [comment]
This solved my problem. Thank you!

**Review by Lloyd-Pottiger — APPROVED** [review]
LGTM

**Review by solotzg — APPROVED** [review]

**Comment by breezewish** [comment]
Shall we cheery pick this to release 6.1 to make life easier?

**Pull request merged**
