### PR TITLE
donot start proxy until cluster is bootstrapped

### LINKED ISSUE #6772: tiflash generate the first region in cluster unexpectly
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start endless cluster using yaml: [testbed.txt](https://github.com/pingcap/tiflash/files/10674633/testbed.txt)
2. You can find sometimes tikv of the cluster keep crashing

### 2. What did you expect to see? (Required)
cluster start ok.
### 3. What did you see instead (Required)
tikv of the cluster keep crashing
### 4. What is your TiFlash version? (Required)
v6.6.0-alpha-393-g7fb79b5091

### PR DESCRIPTION
**Pull request by guo-shaoge**
Signed-off-by: guo-shaoge <shaoge1994@163.com>

### What problem does this PR solve?

Issue Number: close #6772

If a TiFlash starts before any TiKV starts, then the very first Region will be created in TiFlash's proxy and it must be the peer as a leader role. This conflicts with the assumption that tiflash does not contain any Region leader peer and leads to unexpected errors

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below): use endless, just like issue said
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
Suggest change the Problem summary to 
```
If a TiFlash starts before any TiKV starts, then the very first Region will be created in TiFlash's proxy and it must be the peer as a leader role. This conflicts with the assumption that tiflash does not contain any Region leader peer and leads to unexpected errors
```

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
