### PR TITLE
update tiflash proxy

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4879 

Problem Summary:
update proxy to 20220601_161546
### What is changed and how it works?
TiKV implement #4879, update proxy to pick recent changes.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by CalvinNeo** [comment]
should we cherry pick this to TiFlash 6.1?

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by Lloyd-Pottiger** [comment]
> should we cherry pick this to TiFlash 6.1?

I will pick

**Review by JinheLin — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
> should we cherry pick this to TiFlash 6.1?

weiwan says we do need to do that.

**Pull request merged**
