### PR TITLE
cherry pick PR#3283 about sending schemas in exchangeSender

### LINKED ISSUE #3146: TiRemoteBlockInputStream(ExchangeReceiver): different types: expected Nullable(Int64), got Int64
```
Use test;
create table t (id int, d double, nd double not null);
Alter table t set tiflash replica 1;
insert into t values (0,0,0),(1,1,1),(2,null,2);
create table tt like t;
alter table tt set tiflash replica 1;
insert into tt  select * from t;
insert into tt  select * from t;
insert into tt  select * from t;
insert into tt  select * from t;

Select DD,NDD,IDD from tt join 
(
(select d as DD, nd as NDD, id as IDD from t) union all
(select d as DD, 0 as NDD, id as IDD from t) union all
(select d as DD, nd as NDD, 0 as IDD from t) 
) u on tt.id = u.IDD;

mysql> desc Select DD,NDD,IDD from tt join  ( (select d as DD, nd as NDD, id as IDD from t) union all (select d as DD, 0 as NDD, id as IDD from t) union all (select d as DD, nd as NDD, 0 as IDD from t)  ) u on tt.id = u.IDD;
+--------------------------------------------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------+
| id                                         | estRows | task         | access object | operator info                                                                                   |
+--------------------------------------------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------+
| TableReader_65                             | 16.12   | root         |               | data:ExchangeSender_64                                                                          |
| └─ExchangeSender_64                        | 16.12   | cop[tiflash] |               | ExchangeType: PassThrough                                                                       |
|   └─Projection_17                          | 16.12   | cop[tiflash] |               | Column#19, Column#20, Column#21                                                                 |
|     └─HashJoin_63                          | 16.12   | cop[tiflash] |               | inner join, equal:[eq(fzh.tt.id, Column#21)]                                                    |
|       ├─ExchangeReceiver_33(Build)         | 7.80    | cop[tiflash] |               |                                                                                                 |
|       │ └─ExchangeSender_32                | 7.80    | cop[tiflash] |               | ExchangeType: Broadcast                                                                         |
|       │   └─Union_23                       | 7.80    | cop[tiflash] |               |                                                                                                 |
|       │     ├─Projection_24                | 2.40    | cop[tiflash] |               | fzh.t.d, cast(fzh.t.nd, double BINARY)->Column#20, cast(fzh.t.id, bigint(11) BINARY)->Column#21 |
|       │     │ └─Selection_26               | 2.40    | cop[tiflash] |               | not(isnull(cast(fzh.t.id, bigint(11) BINARY)))                                                  |
|       │     │   └─TableFullScan_25         | 3.00    | cop[tiflash] | table:t       | keep order:false                                                                                |
|       │     ├─Projection_27                | 2.40    | cop[tiflash] |               | fzh.t.d, 0->Column#20, cast(fzh.t.id, bigint(11) BINARY)->Column#21                             |
|       │     │ └─Selection_29               | 2.40    | cop[tiflash] |               | not(isnull(cast(fzh.t.id, bigint(11) BINARY)))                                                  |
|       │     │   └─TableFullScan_28         | 3.00    | cop[tiflash] | table:t       | keep order:false                                                                                |
|       │     └─Projection_30                | 3.00    | cop[tiflash] |               | fzh.t.d, cast(fzh.t.nd, double BINARY)->Column#20, 0->Column#21                                 |
|       │       └─TableFullScan_31           | 3.00    | cop[tiflash] | table:t       | keep order:false                                                                                |
|       └─Selection_22(Probe)                | 11.99   | cop[tiflash] |               | not(isnull(fzh.tt.id))                                                                          |
|         └─TableFullScan_21                 | 12.00   | cop[tiflash] | table:tt      | keep order:false                                                                                |
+--------------------------------------------+---------+--------------+---------------+-------------------------------------------------------------------------------------------------+
17 rows in set (0.00 sec)

mysql> Select DD,NDD,IDD from tt join  ( (select d as DD, nd as NDD, id as IDD from t) union all (select d as DD, 0 as NDD, id as IDD from t) union all (select d as DD, nd as NDD, 0 as IDD from t)  ) u on tt.id = u.IDD;
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Block schema mismatch in TiRemoteBlockInputStream(ExchangeReceiver): different types: expected Nullable(Int64), got Int64
mysql>
```

### PR DESCRIPTION
**Pull request by fzhedu**
This is an automated cherry-pick of #3318

### What problem does this PR solve?

Issue Number: close #3146 

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

What's Changed:

### Related changes

- PR to update `pingcap/docs`/`pingcap/docs-cn`:
- Need to cherry-pick to the release branch:

### Check List 

Tests 

- Integration test

Side effects

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by windtalker** [comment]
Don't need to update `tipb`?

**Comment by fzhedu** [comment]
> Don't need to update `tipb`?

 Tue Jan 18 17:59:24 2022 +0800, the HEAD of tipb is newer.

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by fzhedu** [comment]
@VelocityLight PTAL approve

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Pull request merged**
