### PR TITLE
ddl: Support `FLASHBACK DATABASE` (release-7.1)

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/8450

Problem Summary:
tidb support `FLASHBACK DATABASE DBName [TO newDBName]` since v6.4.0 https://docs.pingcap.com/tidb/stable/sql-statement-flashback-database
However, tiflash did not notice that. And if a database is recovered by `FLASHBACK DATABASE`, tiflash can not prevent the data from being removed after gc-safepoint advanced

### What is changed and how it works?

Recover all the tables on the database when `FLASHBACK DATABASE` is executed

Note that the implementation is different from that on master, release-7.5. And it can not handle some (rare) cases that raft-logs come after the database is dropped.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that `FLASHBACK DATABASE` is not applied to TiFlash replica data
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
/hold
need to sync some changes with the master branch PR

**Comment by JaySon-Huang** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/15305/pipeline/
```
[2023-12-04T08:40:43.881Z]   File: fullstack-test2/ddl/multi_alter_with_write.test
[2023-12-04T08:40:43.881Z]   Error line: 472
[2023-12-04T08:40:43.881Z]   Error: DBGInvoke query_mapped('select * from \$d.\$t', test, t)
[2023-12-04T08:40:43.881Z]   Result:
[2023-12-04T08:40:43.881Z]     Received exception from server (version 1.1.54381):
[2023-12-04T08:40:43.881Z]     Code: 0. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Can not find channel for fail point pause_query_init.
[2023-12-04T08:40:43.881Z]   Expected:
[2023-12-04T08:40:43.881Z]     ┌─a───┬─c─────┬─d───┬─e───┐
[2023-12-04T08:40:43.881Z]     │ 1   │ abc   │ 0   │ \N  │
[2023-12-04T08:40:43.881Z]     │ 3   │ ccc   │ 3   │ 0.1 │
[2023-12-04T08:40:43.881Z]     └─────┴───────┴─────┴─────┘
```

**Review by hongyunyan — APPROVED** [review]

**Pull request merged**
