### PR TITLE
fix the wrong order of execution summary for list based executors

### LINKED ISSUE #5241: The order of the executor summary is wrong for the executor list
## Bug Report

In https://github.com/pingcap/tiflash/pull/3937, The type of `profile_streams_map` is changed from `std::map<String, ProfileStreamsInfo>` to `std::unordered_map<String, BlockInputStreams>`. https://github.com/pingcap/tiflash/pull/3937/files#diff-6bc200816961f4a8ad0c24cfaf2d0975ad614e78d153fda6566c44c931908646R263

For executor list, executor_id is in the form of `${i}_${type}`, so the order of `map<executor_id, profile_stream>` is the same as the order of executor list. And the executor summary depends on the order of the executor list.
https://github.com/pingcap/tiflash/blob/f84d7e37e7c850891048ec3efb2cf80e5a32adb3/dbms/src/Flash/Coprocessor/DAGQueryBlock.cpp#L172-L232
https://github.com/pingcap/tiflash/blob/f84d7e37e7c850891048ec3efb2cf80e5a32adb3/dbms/src/Flash/Coprocessor/DAGResponseWriter.cpp#L25

Fortunately, executor list is currently only used in TiSpark :)

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #5241

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the wrong order of execution summary for list based executors.
```

### CODE REVIEW

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by fuzhe1989** [comment]
IMO a customized comparator is needed if you need a strong order guarantee. `$i_$type` will wrongly treat `12_xxx` less than `2_yyy`.

**Comment by SeaRise** [comment]
> IMO a customized comparator is needed if you need a strong order guarantee. `$i_$type` will wrongly treat `12_xxx` less than `2_yyy`.

yes...but for executor list, the num of executor <= 6....

**Comment by SeaRise** [comment]
> IMO a customized comparator is needed if you need a strong order guarantee. `$i_$type` will wrongly treat `12_xxx` less than `2_yyy`.

refactored :)

**Review by gengliqi — APPROVED** [review]

**Review by windtalker — APPROVED** [review]
LGTM

**Pull request merged**
