### PR TITLE
update TiFlash proxy to disable raft-engine

### LINKED ISSUE #4821: Disable raft-engine in TiKV6.0-based TiFlash proxy
## Enhancement

Currently, we have TiFlash proxy based on tikv/4dd5a13e1b7f4f2141abd79d4e4a7e8b5fb7c1a0. However, TiKV has been experienced some modifications since this commit, including disabling raft-engine, which is a great feature. So we need to merge tikv/release-6.0 again.

TiKV has then disabled raft-engine in TiKV 6.0, so we must disable this in Proxy.

Though we don't support downgrade, however, it will cause problems like
```
[2022/05/05 11:03:59.707 +08:00] [FATAL] [setup.rs:320] ["invalid configuration: Found multiple raft data sets: /data1/jiaqizho/tidb-data-jiaqizho/tiflash-36772/flash/raft, /data1/jiaqizho/tidb-data-jiaqizho/tiflash-36772/flash/raft-engine"]
```

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What problem does this PR solve?

Issue Number: close #4821

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by jiaqizho — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
/hold 
Why it uses the branch "raftstore-proxy-6.0-try" instead of "raftstore-proxy-6.0"?

**Comment by CalvinNeo** [comment]
> /hold @CalvinNeo Why it uses the branch "raftstore-proxy-6.0-try" instead of "raftstore-proxy-6.0"?

This is also a temporary branch, just for testing.

**Pull request merged**
