### PR TITLE
Skip first state change of EXCHANGE Partition.

### LINKED ISSUE #7941: Fullstack test `alter_exchange_partition.test` hangs
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After https://github.com/pingcap/tidb/pull/45877, fullstack test `alter_exchange_partition.test` hangs

### PR DESCRIPTION
**Pull request by mjonss**
It only generates warnings/errors and the first state change does not affect TiFlash, it only sets an internal field ExchangePartitionInfo

It is only the second stage transition that is interesting for TiFlash

Should be combined with https://github.com/pingcap/tidb/issues/46125

### What problem does this PR solve?

Issue Number: close #7941

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
https://github.com/pingcap/tiflash/blob/c7bce89b46fdee97dc55ea916d49a2a519d1569e/tests/fullstack-test2/ddl/alter_exchange_partition.test#L15-L16
alter_exchange_partition.test also need to be enabled in this pr

**Review by xzhangxian1008 — APPROVED** [review]
LGTM

**Comment by xzhangxian1008** [comment]
Please format your code with
```
python3 format-diff.py --diff_from `git merge-base xxx/master HEAD`
```

**Review by JaySon-Huang — APPROVED** [review]

**Pull request merged**
