### PR TITLE
PageStorage: fix some tidy

### LINKED ISSUE #6233: Refine code or doc
## Enhancement

just a stub issue, welcome to ref this in your pr when you think it needn't open a new issue.

Don't abuse it!

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #6233 

Problem Summary:

### What is changed and how it works?

use `DB::Logger` instead of `Poco::Logger *`

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Review by JaySon-Huang — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
/hold

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/32299/pipeline

building unit test is broken @Lloyd-Pottiger

**Pull request merged**
