### PR TITLE
*: Keep clang13

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/7193

Problem Summary:

### What is changed and how it works?

Keep using clang 13 before fully tests finished

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by breezewish** [comment]
Why do we still need Clang13?

**Comment by JaySon-Huang** [comment]
> Why do we still need Clang13?

@breezewish  The tests on different platform is not sufficient

**Pull request merged**
