### PR TITLE
Fix unit test `ComputeServerRunner.*` tsan fail

### LINKED ISSUE #6766: Tsan:  false positive in grpc
related: 
- https://github.com/abseil/abseil-cpp/issues/760
- https://github.com/googleapis/google-cloud-cpp/issues/5593#issuecomment-771884933

```
[2022-09-05T18:26:38.094Z] WARNING: ThreadSanitizer: data race (pid=28137)
[2022-09-05T18:26:38.094Z]   Atomic write of size 4 at 0x7fa972e9f340 by thread T1817:
[2022-09-05T18:26:38.094Z]     #0 __tsan_atomic32_fetch_add /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interface_atomic.cpp:611:3 (gtests_dbms+0x2529ba6)
[2022-09-05T18:26:38.094Z]     #1 int std::__1::__cxx_atomic_fetch_add<int>(std::__1::__cxx_atomic_base_impl<int>*, int, std::__1::memory_order) /usr/local/bin/../include/c++/v1/atomic:1060:12 (gtests_dbms+0xcb08ff3)
[2022-09-05T18:26:38.094Z]     #2 std::__1::__atomic_base<int, true>::fetch_add(int, std::__1::memory_order) /usr/local/bin/../include/c++/v1/atomic:1730:17 (gtests_dbms+0xcb08ff3)
[2022-09-05T18:26:38.094Z]     #3 absl::lts_20211102::synchronization_internal::Waiter::Post() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/internal/[waiter.cc:110](http://waiter.cc:110/):14 (gtests_dbms+0xcb08ff3)
[2022-09-05T18:26:38.094Z]     #4 AbslInternalPerThreadSemPost_lts_20211102 /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/internal/[per_thread_sem.cc:73](http://per_thread_sem.cc:73/):64 (gtests_dbms+0xcb086ed)
[2022-09-05T18:26:38.094Z]     #5 absl::lts_20211102::synchronization_internal::PerThreadSem::Post(absl::lts_20211102::base_internal::ThreadIdentity*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/internal/per_thread_sem.h:107:3 (gtests_dbms+0xcb012f4)
[2022-09-05T18:26:38.094Z]     #6 absl::lts_20211102::Mutex::IncrementSynchSem(absl::lts_20211102::Mutex*, absl::lts_20211102::base_internal::PerThreadSynch*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/[mutex.cc:566](http://mutex.cc:566/):3 (gtests_dbms+0xcb012f4)
[2022-09-05T18:26:38.094Z]     #7 absl::lts_20211102::Mutex::Wakeup(absl::lts_20211102::base_internal::PerThreadSynch*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/[mutex.cc:1156](http://mutex.cc:1156/):3 (gtests_dbms+0xcb012f4)
[2022-09-05T18:26:38.094Z]     #8 absl::lts_20211102::Mutex::UnlockSlow(absl::lts_20211102::SynchWaitParams*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/[mutex.cc:2321](http://mutex.cc:2321/):19 (gtests_dbms+0xcb08242)
[2022-09-05T18:26:38.094Z]     #9 absl::lts_20211102::Mutex::Unlock() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/abseil-cpp/absl/synchronization/[mutex.cc:1712](http://mutex.cc:1712/):11 (gtests_dbms+0xcb048ed)
[2022-09-05T18:26:38.094Z]     #10 gpr_mu_unlock /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/gpr/[sync_abseil.cc:61](http://sync_abseil.cc:61/):39 (gtests_dbms+0xc9ce1c9)
[2022-09-05T18:26:38.094Z]     #11 begin_worker(grpc_pollset*, grpc_pollset_worker*, grpc_pollset_worker**, long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/iomgr/[ev_epollex_linux.cc:1052](http://ev_epollex_linux.cc:1052/):3 (gtests_dbms+0xc7396ec)
[2022-09-05T18:26:38.094Z]     #12 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/iomgr/[ev_epollex_linux.cc:1127](http://ev_epollex_linux.cc:1127/):9 (gtests_dbms+0xc7396ec)
[2022-09-05T18:26:38.094Z]     #13 pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/iomgr/[ev_posix.cc:323](http://ev_posix.cc:323/):7 (gtests_dbms+0xc73223e)
[2022-09-05T18:26:38.094Z]     #14 grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/iomgr/[pollset.cc:48](http://pollset.cc:48/):10 (gtests_dbms+0xc7446f3)
[2022-09-05T18:26:38.094Z]     #15 cq_next(grpc_completion_queue*, gpr_timespec, void*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/surface/[completion_queue.cc:1047](http://completion_queue.cc:1047/):29 (gtests_dbms+0xc7eaacb)
[2022-09-05T18:26:38.094Z]     #16 grpc_completion_queue_next /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/core/lib/surface/[completion_queue.cc:1126](http://completion_queue.cc:1126/):10 (gtests_dbms+0xc7e9358)
[2022-09-05T18:26:38.094Z]     #17 grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/src/cpp/common/[completion_queue_cc.cc:146](http://completion_queue_cc.cc:146/):15 (gtests_dbms+0xc486cb9)
[2022-09-05T18:26:38.094Z]     #18 grpc::CompletionQueue::Next(void**, bool*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/grpc/include/grpcpp/impl/codegen/completion_queue.h:185:13 (gtests_dbms+0xae9bd10)
[2022-09-05T18:26:38.094Z]     #19 DB::(anonymous namespace)::handleRpcs(grpc::ServerCompletionQueue*, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:42:25 (gtests_dbms+0xae9bd10)
[2022-09-05T18:26:38.094Z]     #20 DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashSecurityConfig&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&)::$_5::operator()() const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:156:74 (gtests_dbms+0xae9bb9f)
```

### LINKED ISSUE #7388: Tsan: fail in `CollectProcInfoBackgroundTask`
```
  As if synchronized via sleep:
    #0 usleep /root/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:356:3 (gtests_dbms+0x2780c18)
    #1 DB::CollectProcInfoBackgroundTask::end() /data1/huanghaisheng/git-repo/tiflash/dbms/src/Common/BackgroundTask.cpp:95:9 (gtests_dbms+0xe1feec9)
    #2 DB::FlashGrpcServerHolder::~FlashGrpcServerHolder() /data1/huanghaisheng/git-repo/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:240:25 (gtests_dbms+0xc731b4e)
    #3 std::__1::default_delete<DB::FlashGrpcServerHolder>::operator()(DB::FlashGrpcServerHolder*) const /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/unique_ptr.h:57:5 (gtests_dbms+0xca70007)
    #4 std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> >::reset(DB::FlashGrpcServerHolder*) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/unique_ptr.h:318:7 (gtests_dbms+0xca70007)
    #5 std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> >::~unique_ptr() /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/unique_ptr.h:272:19 (gtests_dbms+0xca70007)
    #6 std::__1::pair<unsigned long const, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >::~pair() /data1/huanghaisheng/git-repo/tiflash/contrib/boost/boost/container/detail/std_fwd.hpp:39:8 (gtests_dbms+0xca70007)
    #7 void std::__1::destroy_at<std::__1::pair<unsigned long const, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > > >(std::__1::pair<unsigned long const, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >*) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/construct_at.h:50:13 (gtests_dbms+0xca70007)
    #8 void std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, void*> > >::destroy<std::__1::pair<unsigned long const, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, void, void>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, void*> >&, std::__1::pair<unsigned long const, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >*) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/allocator_traits.h:317:9 (gtests_dbms+0xca70007)
    #9 std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > > > >::__deallocate_node(std::__1::__hash_node_base<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, void*>*>*) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__hash_table:1580:9 (gtests_dbms+0xca70007)
    #10 std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > >, std::__1::equal_to<unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > > > >::clear() /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__hash_table:1826:9 (gtests_dbms+0xca70007)
    #11 std::__1::unordered_map<unsigned long, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> >, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<unsigned long const, std::__1::unique_ptr<DB::FlashGrpcServerHolder, std::__1::default_delete<DB::FlashGrpcServerHolder> > > > >::clear() /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/unordered_map:1277:42 (gtests_dbms+0xca70007)
    #12 DB::tests::MockComputeServerManager::reset() /data1/huanghaisheng/git-repo/tiflash/dbms/src/Debug/MockComputeServerManager.cpp:87:16 (gtests_dbms+0xca70007)
    #13 DB::tests::MPPTaskTestUtils::TearDown() /data1/huanghaisheng/git-repo/tiflash/dbms/src/TestUtils/MPPTaskTestUtils.cpp:46:42 (gtests_dbms+0x5ab37d8)
    #14 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xb5e0a55)
    #15 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xb5e0a55)
    #16 testing::Test::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2525:3 (gtests_dbms+0xb5ba658)
    #17 testing::TestInfo::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xb5bbe24)
    #18 testing::TestCase::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xb5bcaed)
    #19 testing::internal::UnitTestImpl::RunAllTests() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xb5ccca0)
    #20 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xb5e1ef5)
    #21 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xb5e1ef5)
    #22 testing::UnitTest::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xb5cbf88)
    #23 RUN_ALL_TESTS() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x58d7551)
    #24 main /data1/huanghaisheng/git-repo/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:113:16 (gtests_dbms+0x58d7551)

  Thread T663 (tid=12636, finished) created by main thread at:
    #0 pthread_create /root/llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:977:3 (gtests_dbms+0x278347d)
    #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__threading_support:514:10 (gtests_dbms+0xe1ff006)
    #2 std::__1::thread::thread<std::__1::thread DB::ThreadFactory::newThread<void (DB::CollectProcInfoBackgroundTask::*)(), DB::CollectProcInfoBackgroundTask*>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::CollectProcInfoBackgroundTask::*&&)(), DB::CollectProcInfoBackgroundTask*&&)::'lambda'(auto&&...)&, DB::CollectProcInfoBackgroundTask*, void>(void (DB::CollectProcInfoBackgroundTask::*&&)(), DB::CollectProcInfoBackgroundTask*&&) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/thread:307:16 (gtests_dbms+0xe1ff006)
    #3 std::__1::thread DB::ThreadFactory::newThread<void (DB::CollectProcInfoBackgroundTask::*)(), DB::CollectProcInfoBackgroundTask*>(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void (DB::CollectProcInfoBackgroundTask::*&&)(), DB::CollectProcInfoBackgroundTask*&&) /data1/huanghaisheng/git-repo/tiflash/dbms/src/Common/ThreadFactory.h:48:16 (gtests_dbms+0xe1fec5e)
    #4 DB::CollectProcInfoBackgroundTask::begin() /data1/huanghaisheng/git-repo/tiflash/dbms/src/Common/BackgroundTask.cpp:67:25 (gtests_dbms+0xe1fec5e)
    #5 DB::FlashGrpcServerHolder::FlashGrpcServerHolder(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig const&, std::__1::shared_ptr<DB::Logger> const&) /data1/huanghaisheng/git-repo/tiflash/dbms/src/Server/FlashGrpcServerHolder.cpp:132:21 (gtests_dbms+0xc72fba6)
    #6 std::__1::__unique_if<DB::FlashGrpcServerHolder>::__unique_single std::__1::make_unique<DB::FlashGrpcServerHolder, DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig&, std::__1::shared_ptr<DB::Logger> const&>(DB::Context&, Poco::Util::LayeredConfiguration&, DB::TiFlashRaftConfig&, std::__1::shared_ptr<DB::Logger> const&) /data1/huanghaisheng/tiflash-env/sysroot/bin/../include/c++/v1/__memory/unique_ptr.h:728:32 (gtests_dbms+0xca6fc79)
    #7 DB::tests::MockComputeServerManager::startServers(std::__1::shared_ptr<DB::Logger> const&, int) /data1/huanghaisheng/git-repo/tiflash/dbms/src/Debug/MockComputeServerManager.cpp:71:40 (gtests_dbms+0xca6fc79)
    #8 DB::tests::MPPTaskTestUtils::startServers(unsigned long) /data1/huanghaisheng/git-repo/tiflash/dbms/src/TestUtils/MPPTaskTestUtils.cpp:71:42 (gtests_dbms+0x5ab3c94)
    #9 DB::tests::ComputeServerRunner_simpleExchange_Test::TestBody() /data1/huanghaisheng/git-repo/tiflash/dbms/src/Flash/tests/gtest_compute_server.cpp:185:9 (gtests_dbms+0x2c34819)
    #10 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xb5e0a55)
    #11 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xb5e0a55)
    #12 testing::Test::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xb5ba5f5)
    #13 testing::TestInfo::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xb5bbe24)
    #14 testing::TestCase::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xb5bcaed)
    #15 testing::internal::UnitTestImpl::RunAllTests() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xb5ccca0)
    #16 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xb5e1ef5)
    #17 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xb5e1ef5)
    #18 testing::UnitTest::Run() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xb5cbf88)
    #19 RUN_ALL_TESTS() /data1/huanghaisheng/git-repo/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x58d7551)
    #20 main /data1/huanghaisheng/git-repo/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:113:16 (gtests_dbms+0x58d7551)

```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #7388 close #6766

Problem Summary:

### What is changed and how it works?
ref https://github.com/pingcap/tiflash/pull/6864/files#diff-d34a9dab8c425813ed3663fefb4ece983b9210630f517ad23150d3e593874578R66-R75

### Check List

Tests 
`./dbms/gtests_dbms --gtest_filter=ComputeServerRunner.*` tsan passed

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/1057/pipeline

**Review by ywqzzy — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]

**Comment by SeaRise** [comment]
merge

**Pull request merged**
