### PR TITLE
avoid init store when process query for tiflash system tables

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: ref #5665 

Problem Summary: When process query for system tables, tiflash will initialize useless store under `mysql` database. And the data of these stores cannot be cleared manually which make test for data leak problem hard to write.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
LGTM

Do we better backport it to the release-6.1 branch?

**Comment by lidezhu** [comment]
> LGTM
> 
> Do we better backport it to the release-6.1 branch?

This seems really a minor problem. I suggest to not back port it. And the new LTS version is also coming soon.

**Comment by JaySon-Huang** [comment]
> I suggest to not back port it. And the new LTS version is also coming soon.

OK

**Pull request merged**
