### PR TITLE
fix dead lock when do truncate gc on blob file

### LINKED ISSUE #5551: There may be potential dead lock when do truncate gc on blob file
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
If truncate gc was triggered on a BlobFile, it will lock stats before call `getBlobFile` as in https://github.com/pingcap/tiflash/blob/97fa91ff93b07ef2c23f36f93419599047514e10/dbms/src/Storages/Page/V3/BlobStore.cpp#L986. 
https://github.com/pingcap/tiflash/blob/97fa91ff93b07ef2c23f36f93419599047514e10/dbms/src/Storages/Page/V3/BlobStore.cpp#L1002
This may cause dead lock.

### LINKED ISSUE #5552: TiFlash hang
## Bug Report

Please answer these questions before submitting your issue. Thanks!

one of the hang tiflashs process stack is as follows:
[bt.txt](https://github.com/pingcap/tiflash/files/9278207/bt.txt)
image

### 4. What is your TiFlash version? (Required)
6.2

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #5552 

Problem Summary: When interacting with `BlobStat/BlobStats`, there are two locks. One is on `BlobStat` and the other is on `BlobStats`. We must always get lock on BlobStats before lock on BlobStat.
But after we lock `BlobStats` in `getBlobFileParentPath`, we may lock on `BlobStat` before lock on `BlobStats` which may cause deadlock.

### What is changed and how it works?
Avoid lock in `getBlobFileParentPath`.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by lidezhu** [comment]
The problem doesn't exist. Closing it.

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Pull request merged**
