### PR TITLE
Unify the url of submodule to https url

### LINKED ISSUE #4565: Unify the url of submodule to https url
## Enhancement
The git clone protocol of some submodule is ssh,  unify the url of submodule to https url.
```
[submodule "contrib/client-c"]
	path = contrib/client-c
	url = git@github.com:tikv/client-c.git
[submodule "contrib/tiflash-proxy"]
	path = contrib/tiflash-proxy
	url = git@github.com:pingcap/tidb-engine-ext.git
[submodule "contrib/prometheus-cpp"]
	path = contrib/prometheus-cpp
	url = git@github.com:jupp0r/prometheus-cpp.git
```

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>

### What problem does this PR solve?

Issue Number: close #4565

Problem Summary:

### What is changed and how it works?
change url of submodule to https url

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by SeaRise — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]
/LGTM

**Review by solotzg — APPROVED** [review]

**Comment by lightmelodies** [comment]
It seems that the **client-c** submodule should be updated to https://github.com/tikv/client-c/pull/89 too...

**Comment by Lloyd-Pottiger** [comment]
> It seems that the **client-c** submodule should be updated to [tikv/client-c#89](https://github.com/tikv/client-c/pull/89) too...

yes, you are right. Thanks for your advice. Be free to open an issue about it and a associated PR is warmly welcomed!

**Pull request merged**
