### PR TITLE
Set reactor as default config for ExchangeReceiver

### LINKED ISSUE #7507: Switch default AsyncRequestHandler to v1
## Enhancement

Daily random fail point fails with AsyncRequestHandlerV2. Other pr may bring in the bug and we need to close the AsyncRequestHandlerV2 to exclude this circumstance.

### PR DESCRIPTION
**Pull request by xzhangxian1008**
### What problem does this PR solve?

Issue Number: close #7507

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by windtalker — APPROVED** [review]
LGTM

**Comment by Lloyd-Pottiger** [comment]
/hold

please add more description to explain why do the changes, either on issue or on pr.

**Comment by xzhangxian1008** [comment]
> /hold
> 
> please add more description to explain why do the changes, either on issue or on pr.

done

**Pull request merged**
