### PR TITLE
*: Remove embeddedDictionary and ExternalDictionary

### PR DESCRIPTION
**Pull request by ywqzzy**
### What problem does this PR solve?

Issue Number: ref #5628 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ngaut — APPROVED** [review]

**Comment by ywqzzy** [comment]
Question: Is it safe to delete this files?

**Comment by JaySon-Huang** [comment]
> Question: Is it safe to delete this files?

@ywqzzy  I think it is safe. Those files are not used and local dictionary encoding will not be used in the near future.

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Review by zanmato1984 — APPROVED** [review]
LGTM

**Pull request merged**
