### PR TITLE
fix pthread_setname_np

### LINKED ISSUE #6456: RWLock::getLock(): RWLock is already locked in exclusive mode
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

All test passed

### 3. What did you see instead (Required)

https://github.com/pingcap/tiflash/pull/6446
https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/10242/pipeline/299/

```
[2022-12-08T07:14:45.432Z] [2022/12/08 15:14:40.599 +08:00] [DEBUG] [KVStore.cpp:450] ["[region 133] handle ignorable admin command CompactLog at [term: 6, index: 10]"] [thread_id=582]
...
[2022-12-08T07:14:45.434Z] [2022/12/08 15:14:40.893 +08:00] [ERROR] [Exception.cpp:89] ["
Code: 49, e.displayText() = DB::Exception: RWLock::getLock(): RWLock is already locked in exclusive mode, e.what() = DB::Exception, Stack trace:
       0x370815e    StackTrace::StackTrace() [tiflash+57704798]
       0x36f79b2    DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+57637298]
       0xb9eb190    DB::RWLock::getLock(DB::RWLock::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) [tiflash+194949520]
       0xb9e7ee5    DB::IStorage::tryLockTimed(std::__1::shared_ptr<DB::RWLock> const&, DB::RWLock::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) const [tiflash+194936549]
       0xb9e84be    DB::IStorage::lockStructureForShare(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) [tiflash+194938046]
       0xbe90c13    DB::writeRegionDataToStorage(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, std::__1::shared_ptr<DB::Logger> const&)::$_0::operator()(bool) const [tiflash+199822355]
       0xbe8dde0    DB::writeRegionDataToStorage(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, std::__1::shared_ptr<DB::Logger> const&) [tiflash+199810528]
       0xbe8dad5    DB::RegionTable::writeBlockByRegion(DB::Context&, DB::RegionPtrWithBlock const&, std::__1::vector<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> >, std::__1::allocator<std::__1::tuple<DB::RawTiDBPK, unsigned char, unsigned long, std::__1::shared_ptr<DB::StringObject<false> const> > > >&, std::__1::shared_ptr<DB::Logger> const&, bool) [tiflash+199809749]
       0xbed591f    DB::Region::handleWriteRaftCmd(DB::WriteCmdsView const&, unsigned long, unsigned long, DB::TMTContext&) [tiflash+200104223]
       0xbe60e0d    DB::KVStore::handleWriteRaftCmd(DB::WriteCmdsView const&, unsigned long, unsigned long, unsigned long, DB::TMTContext&) [tiflash+199626253]
       0xbe9cd8c    HandleWriteRaftCmd [tiflash+199871884]
  0x7fcb6849ecd7    engine_store_ffi::_$LT$impl$u20$engine_store_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::handle_write_raft_cmd::h2c4b7ab683791bab [libtiflash_proxy.so+71515351]
  0x7fcb684cb150    _$LT$engine_store_ffi..observer..TiFlashObserver$u20$as$u20$raftstore..coprocessor..QueryObserver$GT$::post_exec_query::hcb9f34d07077d569 [libtiflash_proxy.so+71696720]
  0x7fcb6751740c    raftstore::coprocessor::dispatcher::CoprocessorHost$LT$E$GT$::post_exec::h6bc1d3ebb19202fe [libtiflash_proxy.so+55231500]
  0x7fcb66bbbc11    raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::apply_raft_cmd::hf1a9d634cfc7df82 [libtiflash_proxy.so+45419537]
  0x7fcb66bc7d83    raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::process_raft_cmd::hc5a16435da446b8b [libtiflash_proxy.so+45469059]
  0x7fcb66bd4176    raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_entry_normal::h950459aa984d7b26 [libtiflash_proxy.so+45519222]
  0x7fcb66bd504b    raftstore::store::fsm::apply::ApplyDelegate$LT$EK$GT$::handle_raft_committed_entries::h25b2bbe682f9d363 [libtiflash_proxy.so+45523019]
  0x7fcb66badda6    raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_apply::haf944e101a87d824 [libtiflash_proxy.so+45362598]
  0x7fcb66baf162    raftstore::store::fsm::apply::ApplyFsm$LT$EK$GT$::handle_tasks::h48e980651ec4985c [libtiflash_proxy.so+45367650]
  0x7fcb665a1c77    _$LT$raftstore..store..fsm..apply..ApplyPoller$LT$EK$GT$$u20$as$u20$batch_system..batch..PollHandler$LT$raftstore..store..fsm..apply..ApplyFsm$LT$EK$GT$$C$raftstore..store..fsm..apply..ControlFsm$GT$$GT$::handle_normal::hcafa4d28995e63bf [libtiflash_proxy.so+39021687]
  0x7fcb66560551    batch_system::batch::Poller$LT$N$C$C$C$Handler$GT$::poll::h89ede05b6b72fb9c [libtiflash_proxy.so+38753617]
  0x7fcb665573d4    batch_system::batch::BatchSystem$LT$N$C$C$GT$::start_poller::_$u7b$$u7b$closure$u7d$$u7d$::hb028fd34d0ac02f3 [libtiflash_proxy.so+38716372]
  0x7fcb67e87430    _$LT$std..thread..Builder$u20$as$u20$tikv_util..sys..thread..StdThreadBuildWrapper$GT$::spawn_wrapper::_$u7b$$u7b$closure$u7d$$u7d$::h16d6deb5f030a679 [libtiflash_proxy.so+65127472]
  0x7fcb66db5d70    std::sys_common::backtrace::__rust_begin_short_backtrace::h82dcf5fe101025e4 [libtiflash_proxy.so+47492464]
  0x7fcb665bd610    std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::ha59117372e4fa57b [libtiflash_proxy.so+39134736]
  0x7fcb66533124    _$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hf1626431b9fc2487 [libtiflash_proxy.so+38568228]
  0x7fcb671a4122    std::panicking::try::do_call::hdf016785583947cd [libtiflash_proxy.so+51613986]
  0x7fcb675cf66b    __rust_try [libtiflash_proxy.so+55985771]
  0x7fcb67194c15    std::panicking::try::h9d74b4c2de764aae [libtiflash_proxy.so+51551253]
  0x7fcb67189cc4    std::panic::catch_unwind::he3c2a1426560112e [libtiflash_proxy.so+51506372]
  0x7fcb665ba0a6    std::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::h4bb3843b33b4830a [libtiflash_proxy.so+39121062]"] [source="DB::EngineStoreApplyRes DB::HandleWriteRaftCmd(const DB::EngineStoreServerWrap *, DB::WriteCmdsView, DB::RaftCmdHeader)"] [thread_id=582]
```

### 4. What is your TiFlash version? (Required)

master

### LINKED ISSUE #6616: TiFlash crash when preHandleSSTsToDTFiles in CI fullstack test
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Set TiFlash replica. https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/tiflash-ghpr-integration-tests/runs/10529/nodes/182/steps/305/log/?start=0

### 2. What did you expect to see? (Required)
Don't crash.
### 3. What did you see instead (Required)
TiFlash crashed.

`[2023-01-10T03:20:36.216Z] [2023/01/10 11:10:23.602 +08:00] [ERROR] [Exception.cpp:89] ["Code: 49, e.displayText() = DB::Exception: RWLock::getLock(): RWLock is already locked in exclusive mode: physical_table_id=-1: (while preHandleSnapshot region_id=2650, index=7, term=6), e.what() = DB::Exception, Stack trace:\n\n\n       0x37f675e\tStackTrace::StackTrace() [tiflash+58681182]\n       0x37e5fb2\tDB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [tiflash+58613682]\n       0xc3f0480\tDB::RWLock::getLock(DB::RWLock::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) [tiflash+205456512]\n       0xc3ed1d5\tDB::IStorage::tryLockTimed(std::__1::shared_ptr<DB::RWLock> const&, DB::RWLock::Type, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) const [tiflash+205443541]\n       0xc3ed7ae\tDB::IStorage::lockStructureForShare(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> > const&) [tiflash+205445038]\n       0xc897ff0\tDB::AtomicGetStorageSchema(std::__1::shared_ptr<DB::Region> const&, DB::TMTContext&)::$_6::operator()(bool) const [tiflash+210337776]\n       0xc897ac8\tDB::AtomicGetStorageSchema(std::__1::shared_ptr<DB::Region> const&, DB::TMTContext&) [tiflash+210336456]\n       0xc7eb592\tDB::KVStore::preHandleSSTsToDTFiles(std::__1::shared_ptr<DB::Region>, DB::SSTViewVec, unsigned long, unsigned long, DB::DM::FileConvertJobType, DB::TMTContext&) [tiflash+209630610]\n       0xc7eb108\tDB::KVStore::preHandleSnapshotToFiles(std::__1::shared_ptr<DB::Region>, DB::SSTViewVec, unsigned long, unsigned long, DB::TMTContext&) [tiflash+209629448]\n       0xc8a6484\tPreHandleSnapshot [tiflash+210396292]\n  0x7f04d4432930\tengine_store_ffi::_$LT$impl$u20$engine_store_ffi..interfaces..root..DB..EngineStoreServerHelper$GT$::pre_handle_snapshot::h13dfe909d7f6a3ea [libtiflash_proxy.so+76658992]\n  0x7f04d444508d\tengine_store_ffi::observer::pre_handle_snapshot_impl::hccb27a62a7e3c70f [libtiflash_proxy.so+76734605]\n  0x7f04d445a063\t_$LT$engine_store_ffi..observer..TiFlashObserver$u20$as$u20$raftstore..coprocessor..ApplySnapshotObserver$GT$::pre_apply_snapshot::_$u7b$$u7b$closure$u7d$$u7d$::h0f781b1b777e36fa [libtiflash_proxy.so+76820579]\n  0x7f04d44624e1\t_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h7b86279f362c63a3 [libtiflash_proxy.so+76854497]\n  0x7f04d4438b79\tyatp::task::future::RawTask$LT$F$GT$::poll::hef947552eb87fdf3 [libtiflash_proxy.so+76684153]\n  0x7f04d7141ede\tyatp::task::future::TaskCell::poll::h7c797921d1a996a2 [libtiflash_proxy.so+123907806]\n  0x7f04d7142c94\t_$LT$yatp..task..future..Runner$u20$as$u20$yatp..pool..runner..Runner$GT$::handle::h4d1272e83351072c [libtiflash_proxy.so+123911316]\n  0x7f04d7141d43\tyatp::pool::worker::WorkerThread$LT$T$C$R$GT$::run::h7506ebb2efa488d0 [libtiflash_proxy.so+123907395]\n  0x7f04d7128ccd\tyatp::pool::builder::LazyBuilder$LT$T$GT$::build::_$u7b$$u7b$closure$u7d$$u7d$::h4ac5170a13db1e09 [libtiflash_proxy.so+123804877]\n  0x7f04d711c64c\tstd::sys_common::backtrace::__rust_begin_short_backtrace::hcf649c42df4fed43 [libtiflash_proxy.so+123754060]\n  0x7f04d714d1ed\tstd::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h64a73749dd71c9f8 [libtiflash_proxy.so+123953645]\n  0x7f04d711a641\t_$LT$core..panic..unwind_safe..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h85b1ff4258c2deaf [libtiflash_proxy.so+123745857]\n  0x7f04d714d3b6\tstd::panicking::try::do_call::he09d687beb31ad5b [libtiflash_proxy.so+123954102]\n  0x7f04d715fadb\t__rust_try [libtiflash_proxy.so+124029659]\n  0x7f04d714d2df\tstd::panicking::try::hec245749eb3c66e0 [libtiflash_proxy.so+123953887]\n  0x7f04d714ae51\tstd::panic::catch_unwind::h6f4be4704c94ef3b [libtiflash_proxy.so+123944529]\n  0x7f04d714cfba\tstd::thread::Builder::spawn_unchecked_::_$u7b$$u7b$closure$u7d$$u7d$::h2c29f8e8e8dfb511 [libtiflash_proxy.so+123953082]\n  0x7f04d714e627\tcore::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::h5eb0e81e2f12c3b9 [libtiflash_proxy.so+123958823]\n  0x7f04d84fc873\tstd::sys::unix::thread::Thread::new::thread_start::hd2791a9cabec1fda [libtiflash_proxy.so+144595059]\n                \t/rustc/96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef/library/std/src/sys/unix/thread.rs:108\n  0x7f04cf3f8ea5\tstart_thread [libpthread.so.0+32421]\n  0x7f04ced0796d\t__clone [libc.so.6+1042797]"] [source="DB::RawCppPtr DB::PreHandleSnapshot(DB::EngineStoreServerWrap *, DB::BaseBuffView, uint64_t, DB::SSTViewVec, uint64_t, uint64_t)"] [thread_id=50]`

The thread_names created by TiFlash Proxy are `RaftStoreProxy`.
image

### 4. What is your TiFlash version? (Required)
f9167f36641360530425459c2e0e0b4ad4750841 in master branch

### PR DESCRIPTION
**Pull request by hehechen**
Signed-off-by: hehechen <awd123456sss@gmail.com>

### What problem does this PR solve?

Issue Number: close #6616 close #6456

Problem Summary:
The `pthread_setname_np` symbol in TiFlash Proxy will be overwritten by https://github.com/pingcap/tiflash/blob/9b8503bca9665b66ffcfef39f3c406dcf560c709/libs/libglibc-compatibility/glibc-compatibility.c#L144, which will cause the thread names of Proxy all same and casue TiFlash crash when get RWLock.
There is no problem in release version because there is `-fvisibility=hidden` flag in release version.
### What is changed and how it works?
Remove `pthread_setname_np` in https://github.com/pingcap/tiflash/blob/9b8503bca9665b66ffcfef39f3c406dcf560c709/libs/libglibc-compatibility/glibc-compatibility.c#L144. Because the [glibc version](https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements) required for running TiDB (including TiFlash) [has supported `pthread_setname_np` function](https://reviews.llvm.org/D30844).
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
Build TiFlash with 
`cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=RELWITHDEBINFO`
and check the thread name of TiFlash Proxy
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

**Review by CalvinNeo — APPROVED** [review]

**Comment by CalvinNeo** [comment]
Should we fix the RWLock behavior here?

**Comment by hehechen** [comment]
> Should we fix the RWLock behavior here?

will fix after this discussion https://github.com/pingcap/tiflash/issues/6631 .

**Pull request merged**
