### PR TITLE
Fix two DDL bugs on hotfix branch

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/5154, close https://github.com/pingcap/tiflash/issues/5859

Problem Summary:

cherry-pick two bug fixes for DDL:
* For #5154
  * https://github.com/pingcap/tiflash/pull/5191
* For #5859
  * https://github.com/pingcap/tiflash/pull/5932
  * https://github.com/pingcap/tiflash/pull/5924

### Check List

Tests 

- [ ] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by flowbehappy — APPROVED** [review]

**Review by hongyunyan — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
close as the user plan to upgrade to v5.4.3 which include these fixes

**Pull request merged**
