### PR TITLE
Fix typo in README/build

### LINKED ISSUE #4560: Fix typo in README/build
## Enhancement
Change
```
cd $BUILD
cmake $WORKSPACE/tiflash -Gninja
ninja tiflash
```
to
```
cd $BUILD
cmake $WORKSPACE/tiflash -GNinja
ninja tiflash
```

### PR DESCRIPTION
**Pull request by qian0817**
### What problem does this PR solve?

Issue Number: close #4560

Problem Summary: Fix typo about build in README.

### What is changed and how it works?

Fix typo about build in README.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ywqzzy — APPROVED** [review]

**Review by zanmato1984 — APPROVED** [review]
LGTM, and thanks for being our first contributor from community!

**Review by LittleFall — APPROVED** [review]

**Review by solotzg — APPROVED** [review]
lgtm

**Comment by qian0817** [comment]
Wow, I'm surprised and glad to be the first contributor!

**Pull request merged**
