### PR TITLE
use logical cores as max_threads

### LINKED ISSUE #8159: use logical cores as computing concurrency
## Enhancement
Better to use logical cores so we can fully utilize physical resources.
For machines with 4 physical cores, it may have 8 physical threads.

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #8159

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
It used to be the number of logical CPU, but has been changed to number of physical CPU in https://github.com/pingcap/tiflash/pull/6481/files

**Comment by SeaRise** [comment]
- arm
vSjA8VoZWQ
- amd
92c4c95f-4d69-4339-be39-eb80e815df01

It seems that the performance under arm can be improved by nearly 50%

**Review by SeaRise — APPROVED** [review]
/lgtm

**Review by xzhangxian1008 — APPROVED** [review]
LGTM

**Pull request merged**
