### PR TITLE
testing: pageworkload `HeavySkewWriteRead` support deleting data

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/6163

Problem Summary:
We do not delete the page and update existing pages in the previous pageworkload `HeavySkewWriteRead`. It always appends new pages. So it can not simulate the real workload of delta-tree and cost lots of disk space.

We want to use this workload for verifying the bugs reported in https://github.com/pingcap/tiflash/issues/6163

### What is changed and how it works?
* Keep track of page id committed to PageStorage
* Update pages for about 
* Remove the pages if that is unlikely to be updated or read anymore
* Previously, `PSWriter::updatedRandomData` generate random data for updating and reading with a bytes length range of [0, buffer_size_max]. Now it is replaced by `PSWriter::getRandomData` and the bytes length range is limited in [buffer_size_min, buffer_size_max]. The random data has a smaller range and more stable reading/writing speed.

The read/write performance:
```
W: 633028 pages, 618.1914 GB, 0.6182 GB/s
R: 31338450 pages, 30603.9551 GB, 30.6035 GB/s

W: 641408 pages, 626.3750 GB, 0.6264 GB/s
R: 30543630 pages, 29827.7637 GB, 29.8274 GB/s

W: 648852 pages, 633.6445 GB, 0.6336 GB/s
R: 29991155 pages, 29288.2373 GB, 29.2879 GB/s
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

I run the workload for 20 minutes. After the workload ends, the remaining page num is 757 rather than a large number of pages. And the disk space used for this testing is more reasonable.
```
> ./dbms/src/Server/tiflash pageworkload -M 16 --clean_before_run 1 --gc_interval 5 --avg_page_size 4096 --timeout 1200 &> workload.log
> cat workload.log
....
[2022/10/25 02:30:32.151 +08:00] [INFO] [PageDirectory.cpp:1461] ["After MVCC gc in memory [lowest_seq=4164205] clean [invalid_snapshot_nums=0] [invalid_page_nums=16336] [total_deref_counter=0] [all_del_entries=101659]. Still exist [snapshot_nums=0], [page_nums=757]. Longest alive snapshot: [longest_alive_snapshot_time=0] [longest_alive_snapshot_seq=0] [stale_snapshot_nums=0]"] [source=stress_test] [thread_id=23]
>  du -sh stress/HeavySkewWriteRead/*
145M    stress/HeavySkewWriteRead/blobfile_65
13M     stress/HeavySkewWriteRead/blobfile_66
3.0M    stress/HeavySkewWriteRead/blobfile_67
93M     stress/HeavySkewWriteRead/wal
>  du -sh stress/HeavySkewWriteRead/*/*
88M     stress/HeavySkewWriteRead/wal/log_280_1
2.1M    stress/HeavySkewWriteRead/wal/log_281_0
2.1M    stress/HeavySkewWriteRead/wal/log_282_0
944K    stress/HeavySkewWriteRead/wal/log_283_0
```

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by flowbehappy** [comment]
Is it possible to report the bug automatically? Like by checking the wal file size.

**Comment by JaySon-Huang** [comment]
> Is it possible to detect the bug automatically? Like by checking the wal file size.

I add some metrics about the WAL log file size in this PR https://github.com/pingcap/tiflash/pull/6175. We can add some checks after that.

**Review by lidezhu — APPROVED** [review]

**Review by hehechen — APPROVED** [review]

**Pull request merged**
