### PR TITLE
remove useless arrayJoin

### LINKED ISSUE #4860: Interpreter useless code removal
## Enhancement
There are many interpreter class from upstream clickhouse that are not used.
For code readability, It's better to drop all of them.

There are several types of interpreter class, they are listed as follow:

1. SelectQuery
2. AlterQuery
3. DropQuery
4. CreateQuery
5. RenameQuery
6. ManageQuery
7. ShowTablesQuery
8. OptimizeQuery #4589 
9. TruncateQuery #4587 
10. TableProperties #4586 
11. CheckQuery #4569 #4568 
12. KillQUery #4567  #4564 
13. SystemQuery #4590 
14. UseQuery
15. SetQuery
16.  DeleteQuery #4589 
17. DescribeQuery
18. ExistQuery
19. InsertQuery
20. ShowProcesslist

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>

### What problem does this PR solve?

Issue Number: close #4860

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by SeaRise — APPROVED** [review]
LGTM

**Comment by ywqzzy** [comment]
Good job! More is better!

**Review by ywqzzy — APPROVED** [review]

**Pull request merged**
