### PR TITLE
change the time unit of measurement in ScanContext

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: ref #5926

Problem Summary:

### What is changed and how it works?

Change the time unit of measurement in ScanContext.
Choose ns instead of ms as the time unit can improve the accuracy of statistics.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
Could you please give the reason about why do this?

**Review by breezewish — APPROVED** [review]

**Comment by hongyunyan** [comment]
> Could you please give the reason about why do this?

Choose ns instead of ms as the time unit can improve the accuracy of statistics.

**Comment by hongyunyan** [comment]
> Could you please give the reason about why do this?

Choose ns instead of ms as the time unit can improve the accuracy of statistics.

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
