### PR TITLE
Avoid useless `transform` operations when block's row count is 0

### PR DESCRIPTION
**Pull request by gengliqi**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/6233

Problem Summary:

### What is changed and how it works?
This change may cause an issue that a sink does not get any block after execution. Hence, some tests failed.
So I change the `columnsEqual` to make the empty-column block equal to the empty-row block.

```commit-message
Avoid useless `tranform` operations when block's row count is 0
```

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by windtalker — APPROVED** [review]
lgtm

**Comment by Lloyd-Pottiger** [comment]
`tranform` --> `transform`?

**Review by yibin87 — APPROVED** [review]
LGTM

**Pull request merged**
