### PR TITLE
Use SquashingBlockInputStream for delta stream in fast mode

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: ref #5252 

Problem Summary:

### What is changed and how it works?

use SquashingBlockInputStream for delta stream in fast mode.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by flowbehappy** [comment]
We will need some benchmark results before merging it. @hongyunyan

**Comment by hongyunyan** [comment]
Yes! This PR is now for benchbot test.

**Review by flowbehappy — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request closed without merging**
