### PR TITLE
*: Remove useless column serialize format

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #6233

Problem Summary:

### What is changed and how it works?

```commit-message
*: Remove useless column serialize format
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
What is the format that tiflash returns the system table query result to tidb? Is that still workable after we remove the "CSV" serializer?

**Comment by Lloyd-Pottiger** [comment]
> What is the format that tiflash returns the system table query result to tidb? Is that still workable after we remove the "CSV" serializer?

JSON

**Review by JaySon-Huang — APPROVED** [review]

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Review by yudongusa — APPROVED** [review]
LGTM. Please don't forget changing the document.

**Comment by JaySon-Huang** [comment]
@yudongusa The changes in this PR are legacy codes and settings introduced by the clickhouse codebase. Because the settings `input_format_skip_unknown_fields` have no meaning for the user of tiflash, this setting is not public announced in the documents of pingcap/tiflash.
So there is no need to change the documents of pingcap/tiflash.

**Pull request merged**
