### PR TITLE
update proxy of release-6.1 to raftstore-proxy-6.1

### LINKED ISSUE #5646: TiFlash Proxy may OOM/bcast too many messages/drop apply res
## Bug Report

Please answer these questions before submitting your issue. Thanks!

There bugs are all derived from TiKV:
https://github.com/tikv/tikv/issues/13160
https://github.com/tikv/tikv/pull/12247
https://github.com/tikv/tikv/pull/13193

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #5646

Problem Summary:
Update proxy on 6.1 to take advantage of fix from https://github.com/pingcap/tidb-engine-ext/pull/135

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lidezhu — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
lgtm

You may create a standalone issue for getting a triage approve to release-6.1 branch

**Review by flowbehappy — APPROVED** [review]

**Comment by CalvinNeo** [comment]
> lgtm
> 
> You may create a standalone issue and describe the details of fixed probelm for getting a triage approval to release-6.1 branch

Fixed

**Pull request merged**
