### PR TITLE
[TIFLASH #4562] Remove embedded member function for gtest in `dbms/src/Storages/Page`

### LINKED ISSUE #4562: Remove embedded member function for gtest in `dbms/src/Storages/Page`
## Enhancement
There are some embedded member function in the directory `dbms/src/Storages/Page`
like `PS::V3::PageStorageImpl`
```cpp=74
#ifndef NDEBUG
    // Just for tests, refactor them out later
    DB::PageStorage::SnapshotPtr getSnapshot() { return getSnapshot(""); }
    DB::PageEntry getEntry(PageId page_id) { return getEntryImpl(TEST_NAMESPACE_ID, page_id, nullptr); }
    DB::Page read(PageId page_id) { return readImpl(TEST_NAMESPACE_ID, page_id, nullptr, nullptr); }
    PageMap read(const std::vector<PageId> & page_ids) { return readImpl(TEST_NAMESPACE_ID, page_ids, nullptr, nullptr); }
    void read(const std::vector<PageId> & page_ids, const PageHandler & handler) { return readImpl(TEST_NAMESPACE_ID, page_ids, handler, nullptr, nullptr); }
    PageMap read(const std::vector<PageReadFields> & page_fields) { return readImpl(TEST_NAMESPACE_ID, page_fields, nullptr, nullptr); }
#endif
```
which is just for tests. This is not a elegant code style, and we need to remove them.

### PR DESCRIPTION
**Pull request by SteNicholas**
### What problem does this PR solve?

Issue Number: close #4562 

Problem Summary: Remove embedded member function for gtest in `dbms/src/Storages/Page`

### What is changed and how it works?

Remove embedded member functions for gtest in `dbms/src/Storages/Page` including `PS::V2::PageStorage`, `PS::V3::PageDirectory`, `PS::V3::PageEntriesEdit` and `PS::V3::PageStorageImpl`.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by LittleFall — APPROVED** [review]

**Review by Lloyd-Pottiger — CHANGES_REQUESTED** [review]
I don't think it works, the brief solution have mentioned  https://github.com/pingcap/tiflash/issues/4562#issuecomment-1086507184

**Comment by Lloyd-Pottiger** [comment]
The way to run unit tests
```
cd $BUILD
cmake $WORKSPACE/tiflash -GNinja -DCMAKE_BUILD_TYPE=DEBUG
ninja gtests_dbms
./dbms/gtests_dbms
```

**Review by LittleFall — COMMENTED** [review]
agree with another review comment,  lgtm canceled temporarly.

**Comment by Lloyd-Pottiger** [comment]
It has been a long day since last update. @SteNicholas are u still working on it?

**Comment by Lloyd-Pottiger** [comment]
Seems that you are not working on it now. And this pr does not work, so I would close it and cancel assign tomorrow.

**Pull request closed without merging**
