### PR TITLE
Fix tsan fail in unit test `EventTestRunner.base`

### LINKED ISSUE #6743: Tsan fail in unit test `EventTestRunner.base`
## Bug Report

tsan fail in `EventTestRunner.base`
```
[2023-02-05T18:05:24.880Z] WARNING: ThreadSanitizer: data race (pid=27690)
[2023-02-05T18:05:24.880Z]   Write of size 8 at 0x7ffd8946adf8 by main thread:
[2023-02-05T18:05:24.880Z]     #0 pthread_cond_destroy /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1258:3 (gtests_dbms+0x23bc79a)
[2023-02-05T18:05:24.880Z]     #1 DB::PipelineExecutorStatus::~PipelineExecutorStatus() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Executor/PipelineExecutorStatus.h:24:7 (gtests_dbms+0x2781ffb)
[2023-02-05T18:05:24.880Z]     #2 DB::tests::EventTestRunner_base_Test::TestBody()::$_0::operator()(unsigned long, unsigned long) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp:372:5 (gtests_dbms+0x2781ffb)
[2023-02-05T18:05:24.880Z]     #3 DB::tests::EventTestRunner_base_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp:376:13 (gtests_dbms+0x2781ffb)
[2023-02-05T18:05:24.880Z]     #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xaa32095)
[2023-02-05T18:05:24.880Z]     #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xaa32095)
[2023-02-05T18:05:24.880Z]     #6 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xaa0bc35)
[2023-02-05T18:05:24.880Z]     #7 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xaa0d464)
[2023-02-05T18:05:24.880Z]     #8 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xaa0e12d)
[2023-02-05T18:05:24.880Z]     #9 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xaa1e2e0)
[2023-02-05T18:05:24.880Z]     #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xaa33535)
[2023-02-05T18:05:24.880Z]     #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xaa33535)
[2023-02-05T18:05:24.880Z]     #12 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xaa1d5c8)
[2023-02-05T18:05:24.880Z]     #13 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x654c7c9)
[2023-02-05T18:05:24.880Z]     #14 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:78:16 (gtests_dbms+0x654c7c9)
[2023-02-05T18:05:24.880Z] 
[2023-02-05T18:05:24.880Z]   Previous read of size 8 at 0x7ffd8946adf8 by thread T46:
[2023-02-05T18:05:24.880Z]     #0 pthread_cond_broadcast /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:1251:3 (gtests_dbms+0x23bc627)
[2023-02-05T18:05:24.880Z]     #1 DB::PipelineExecutorStatus::onEventFinish() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Executor/PipelineExecutorStatus.cpp:65:12 (gtests_dbms+0xcf6c1d8)
[2023-02-05T18:05:24.880Z]     #2 DB::Event::finish() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:103:17 (gtests_dbms+0xcf90433)
[2023-02-05T18:05:24.881Z]     #3 DB::Event::onTaskFinish() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/Events/Event.cpp:121:9 (gtests_dbms+0xcf9075b)
[2023-02-05T18:05:24.881Z]     #4 DB::EventTask::~EventTask() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/Tasks/EventTask.cpp:33:12 (gtests_dbms+0xcf944b0)
[2023-02-05T18:05:24.881Z]     #5 DB::tests::(anonymous namespace)::BaseTask::~BaseTask() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/Events/tests/gtest_event.cpp:27:7 (gtests_dbms+0x2789399)
[2023-02-05T18:05:24.881Z]     #6 std::__1::default_delete<DB::Task>::operator()(DB::Task*) const /usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:57:5 (gtests_dbms+0xcf8ba07)
[2023-02-05T18:05:24.881Z]     #7 std::__1::unique_ptr<DB::Task, std::__1::default_delete<DB::Task> >::reset(DB::Task*) /usr/local/bin/../include/c++/v1/__memory/unique_ptr.h:318:7 (gtests_dbms+0xcf8ba07)
[2023-02-05T18:05:24.881Z]     #8 DB::TaskThreadPool::handleTask(std::__1::unique_ptr<DB::Task, std::__1::default_delete<DB::Task> >&, std::__1::shared_ptr<DB::Logger> const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp:92:14 (gtests_dbms+0xcf8ba07)
[2023-02-05T18:05:24.881Z]     #9 DB::TaskThreadPool::loop(unsigned long) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Flash/Pipeline/Schedule/TaskThreadPool.cpp:60:9 (gtests_dbms+0xcf8b260)
[2023-02-05T18:05:24.881Z]     #10 decltype(*(static_cast<DB::TaskThreadPool*>(fp0)).*fp(static_cast<unsigned long>(fp1))) std::__1::__invoke<void (DB::TaskThreadPool::*)(unsigned long) noexcept, DB::TaskThreadPool*, unsigned long, void>(void (DB::TaskThreadPool::*&&)(unsigned long) noexcept, DB::TaskThreadPool*&&, unsigned long&&) /usr/local/bin/../include/c++/v1/type_traits:3859:1 (gtests_dbms+0xcf8ca10)
[2023-02-05T18:05:24.881Z]     #11 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::TaskThreadPool::*)(unsigned long) noexcept, DB::TaskThreadPool*, unsigned long, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::TaskThreadPool::*)(unsigned long) noexcept, DB::TaskThreadPool*, unsigned long>&, std::__1::__tuple_indices<2ul, 3ul>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xcf8ca10)
[2023-02-05T18:05:24.881Z]     #12 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::TaskThreadPool::*)(unsigned long) noexcept, DB::TaskThreadPool*, unsigned long> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xcf8ca10)
[2023-02-05T18:05:24.881Z] 
[2023-02-05T18:05:24.881Z]   Location is stack of main thread.
[2023-02-05T18:05:24.881Z] 
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #6743

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/854/pipeline/

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by ywqzzy — APPROVED** [review]

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/860/pipeline

**Pull request merged**
