### PR TITLE
fix read from ColumnFileBigReader

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: ref #5252 

Problem Summary: Currently `ColumnFileBigReader::readNextBlock` doesn't work normally when just read two columns, because we never call `readNextBlock` when we just need read pk and version column.
But after support fast mode, there is a chance that the previous scenario happens. So we must fix it.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JaySon-Huang** [comment]
> But after support fast mode, there is a chance that the previous scenario happens

To be more specific, is it mean that under normal mode, at least we read 3 columns `<pk, tag, version>`. But for fast mode, we may only read `<pk, tag>`. And this bug will make the `select count(*) from t` return the wrong result?

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Comment by hongyunyan** [comment]
LGTM

**Comment by lidezhu** [comment]
> > But after support fast mode, there is a chance that the previous scenario happens
> 
> To be more specific, is it mean that under normal mode, at least we read 3 columns `<pk, tag, version>`. But for fast mode, we may only read `<pk, tag>`. And this bug will make the `select count(*) from t` return the wrong result?

Yes

**Review by hongyunyan — APPROVED** [review]

**Pull request merged**
