### PR TITLE
Fix compilation error on macOS m1 due to sprintf

### LINKED ISSUE #6488: Compilation on Apple M1 met an error due to usage of sprintf in boost/program_options.hpp
## Enhancement
To allow compilation of tiflash on Apple M1

while doing direct compilation on Apple M1 with "cmake .. -GNinja -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_SYSTEM_PROCESSOR=AARCH64" plus ninja, the following error happened
`
In file included from /Users/ning/tidb-repos/tiflash/dbms/src/Storages/Page/tools/PageCtl/MainEntry.cpp:21:
In file included from /Users/ning/tidb-repos/tiflash/libs/libcommon/include/boost_wrapper/program_options.h:22:
In file included from /Users/ning/tidb-repos/tiflash/contrib/boost/boost/program_options.hpp:15:
In file included from /Users/ning/tidb-repos/tiflash/contrib/boost/boost/program_options/options_description.hpp:13:
In file included from /Users/ning/tidb-repos/tiflash/contrib/boost/boost/program_options/value_semantic.hpp:14:
In file included from /Users/ning/tidb-repos/tiflash/contrib/boost/boost/lexical_cast.hpp:32:
In file included from /Users/ning/tidb-repos/tiflash/contrib/boost/boost/lexical_cast/try_lexical_convert.hpp:44:
In file included from /Users/ning/tidb-repos/tiflash/contrib/boost/boost/lexical_cast/detail/converter_lexical.hpp:54:
/Users/ning/tidb-repos/tiflash/contrib/boost/boost/lexical_cast/detail/converter_lexical_streams.hpp:297:21: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                    sprintf(begin,
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
`

### PR DESCRIPTION
**Pull request by xuning97**
On macOS m1, while compile tiflash, [-Werror,-Wdeprecated-declarations] will be triggered compiling MainEntry.cpp

Since MainEntry.cpp includes boost program_options.h, which leads to
converter_lexical_streams.hpp, and this file uses 'sprintf', and same thing happens to stdio.h
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here

### What problem does this PR solve?
Fix compilation error on MacOS M1

Issue Number: close #6488 

Problem Summary:

### What is changed and how it works?

Just turn -Werror,-Wdeprecated-declarations into warning through GCC diagnostic

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by windtalker — APPROVED** [review]
LGTM

**Review by Lloyd-Pottiger — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
@xuning97 thanks for your contribution, could you please sign the cla? https://cla.pingcap.net/pingcap/tiflash?pullRequest=6487

**Comment by xuning97** [comment]
> @xuning97 thanks for your contribution, could you please sign the cla? https://cla.pingcap.net/pingcap/tiflash?pullRequest=6487

Thanks for your reminder, I've signed the CLA

**Pull request merged**
