### PR TITLE
metrics: remove batch item in metrics

### PR DESCRIPTION
**Pull request by LittleFall**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/6233

Problem Summary: batch item in metrics is useless.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

before
image
after
image

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ywqzzy — APPROVED** [review]

**Review by SeaRise — APPROVED** [review]
/merge

**Review by gengliqi — APPROVED** [review]

**Review by mengxin9014 — APPROVED** [review]

**Pull request merged**
