### PR TITLE
tests: add tests for timestamp with timezone

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #6233

Problem Summary:

### What is changed and how it works?

Before, there is a bug which cause those tests failed, so in https://github.com/pingcap/tiflash/pull/8925 we remove those tests. Now https://github.com/pingcap/tidb/pull/52502 fixed, we can add those tests back.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by yibin87 — APPROVED** [review]
LGTM

**Review by JaySon-Huang — APPROVED** [review]

**Comment by yibin87** [comment]
C5vo4Rs845
Still not using the latest tidb image

**Pull request merged**
