### PR TITLE
Rename filename to UniThreadPool to fix build on mac

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflash/issues/6827

Problem Summary:
After https://github.com/pingcap/tiflash/pull/6942, `common/ThreadPool.h` is conflicts with `Common/ThreadPool.h`.

And replacing the old thread pool, the unit test hangs when exiting https://github.com/pingcap/tiflash/pull/6948.

### What is changed and how it works?

* Rename `Common/ThreadPool.h` to `Common/UniThreadPool.h`
* Leave `common/ThreadPool.h` not changed
* Remove some useless tests and include header

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
  - [x] Build on my m1 mac is OK
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by breezewish — APPROVED** [review]

**Comment by breezewish** [comment]
Another way is that, may be we could just remove the old thread pool.

**Review by lidezhu — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]

**Comment by JaySon-Huang** [comment]
> Another way is that, may be we could just remove the old thread pool, just like what we did in the cn_mvp branch.

I've tried in this PR https://github.com/pingcap/tiflash/pull/6960#issuecomment-1455471239, but the unit test run on CI hangs when exiting.

We can remove the old one later

**Pull request merged**
