### PR TITLE
.*: Separate `TemporaryFileStream` from `AggregatingBlockInputStream/ParallelAggregatingBlockInputStream`

### LINKED ISSUE #5887: `TemporaryFileStream` repeated in `AggregatingBlockInputStream` and `ParallelAggregatingBlockInputStream `

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #5887

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by ywqzzy — APPROVED** [review]
LGTM. When will we use TemporaryFileStream?

**Comment by SeaRise** [comment]
> LGTM. When will we use TemporaryFileStream?

Currently agg result will not be written to disk, so it will not be used...

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
