### PR TITLE
BlobStore change the selection strategy.

### PR DESCRIPTION
**Pull request by jiaqizho**
### What problem does this PR solve?

Issue Number: ref #3594 

Problem Summary:

image
In multi-paths, BlobStore always chooses the lowest valid_rate to write. Then it will make the data imbalance.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by jiaqizho** [comment]
@JaySon-Huang 
change back to the strategy
1. choose the path.
2. find the stat in the current path.

Is that make sense?

**Comment by JaySon-Huang** [comment]
IMO, these changes don't make data to be more balance🤔

**Comment by JaySon-Huang** [comment]
maybe we should iterate all path, and try to get "the smallest valid_rate inside each path" instead of "the smallest valid_rate among all paths"?
More specified, move line 1138 into the `for (path_iter_idx = 0; path_iter_idx < stats_map.size(); ++path_iter_idx)` loop

**Comment by jiaqizho** [comment]
> maybe we should iterate all path, and try to get "the smallest valid_rate inside each path" instead of "the smallest valid_rate among all paths"? More specified, move line 1138 into the `for (path_iter_idx = 0; path_iter_idx < stats_map.size(); ++path_iter_idx)` loop

I am not sure whether I got your point. These changes' main logic is:

1. round-robin to choose the path
2. select a `BlobStat` by `valid_rate` from the current path. If can't find one, create a new `blobstat`

old logic is:

1. loop all `BlobStat` and find the lowest `valid_rate` one.
2. if can't find create a new one.

**Comment by jiaqizho** [comment]
not root case I thought.

**Pull request closed without merging**
