### PR TITLE
remove IfNull duplicated implementation 

### LINKED ISSUE #6037: Possible Duplication in Function `IfNull`
## Enhancement

I find two implementation of `IfNull` function:
- one is a reusage in tiflash: https://github.com/pingcap/tiflash/blob/973de13fef5e787be1f2867f2a4fbb4af20ee77d/dbms/src/Flash/Coprocessor/DAGExpressionAnalyzerHelper.cpp#L435-L458
- one is from clickhouse: https://github.com/pingcap/tiflash/blob/master/dbms/src/Functions/FunctionsNull.h + https://github.com/pingcap/tiflash/blob/master/dbms/src/Functions/FunctionsNull.cpp 

I did some experiments to see that the implementation from clickhouse is actually not used at all. But I still not sure if the IfNull from clickhouse can be removed? So we can discuss about it.

### PR DESCRIPTION
**Pull request by JigaoLuo**
### What problem does this PR solve?

Issue Number: close #6037
Problem Summary:

### What is changed and how it works?

Check if the IfNull from clickhouse can be removed.

I did check the unit test and the integration test on `IfNull` locally. I can pass them locally.

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]
lgtm

**Review by windtalker — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]

**Comment by JigaoLuo** [comment]
Why are the test failing?
- https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-integration-tests/detail/tiflash-ghpr-integration-tests/9325/pipeline/261
- https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/13581/pipeline

**Pull request merged**
