### PR TITLE
Disable ingest range check

### PR DESCRIPTION
**Pull request by breezewish**
Signed-off-by: Wish <breezewish@outlook.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/6507

Problem Summary:

Consider that we have a clustered table:

```sql
CREATE TABLE t (a VARCHAR(2), b BIGINT, PRIMARY KEY(a, b) CLUSTERED);
insert into t values ("a", 1), ("a", 2), ("a", 3), ("a", 4), ("a", 5);
```

In normal cases, suppose we have a split at record `("a", 4)`, the region range (MemComparable decoded) would be:

```
74 8000000000000046 5f72                                           (Region Range Begin)
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000005 (Region Range End)
t                   _ r  Bytes("a")            Int(4)
```

For this region, these keys are included:

```
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000001
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000002
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000003
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000004
                                                                ^^
```

When we use `PrefixNext()` to calculate the FileRange from the data, we would have:

```
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000001 (FileRange Begin)
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000005 (FileRange End)
```

However, it appears that we may meet an irregular region range in some cases (possibly caused by Lightning import, it should be never caused by TiKV auto split or TiDB split syntax):

```
74 8000000000000046 5f72                                              (Region Range Begin)
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000004 00 (Region Range End)
```

This kind of region range also contains the data exactly, but is smaller than the FileRange, causing Assertion to fail.

### What is changed and how it works?

Disable the check. We will work out some better checks in later DMR versions.

The disabling is safe because:

1. For InegstBySplit, we naturally support RegionRange<FileRange.
2. For IngestByColumnFile, the actual FileRange is < RegionRange, so that we will not accidentally delete anything outside the ingest file.

There could be a change to just change from `toPrefixNext` to `toNext`. However it only works for CommonHandle, but not IntHandle.

CommonHandle Case:

```
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000001    (FileRange Begin)
74 8000000000000046 5f72 01 6100000000000000f8 03 8000000000000004 00 (FileRange End)
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

I cannot reproduce how this region range is produced using TiDB, so I use tikv-ctl to force generate such regions.

Common handle:

```
$>   tiup playground v6.4.0 --tiflash.binpath cmake-build-debug/dbms/src/Server/tiflash
sql> CREATE TABLE t (a VARCHAR(2), b BIGINT, PRIMARY KEY(a, b) CLUSTERED);
sql> INSERT INTO t VALUES ("a", 1), ("a", 2), ("a", 3), ("a", 4), ("a", 5);
$>   bin/tikv-ctl --pd=127.0.0.1:2379 split-region -r=10 -k='t\200\000\000\000\000\000\000F_r\001a\000\000\000\000\000\000\000\370\003\200\000\000\000\000\000\000\004\000'
                                                   ^^^^^ you may need to set region id properly
sql> ALTER TABLE t SET TIFLASH REPLICA 1;
```

Int handle:

```
$>   tiup playground v6.4.0 --tiflash.binpath cmake-build-debug/dbms/src/Server/tiflash
sql> CREATE TABLE t (a BIGINT, PRIMARY KEY(a) CLUSTERED);
sql> INSERT INTO t VALUES (1), (2), (3), (4), (5);
$>   bin/tikv-ctl --pd=127.0.0.1:2379 split-region -r=10 -k='t\200\000\000\000\000\000\000F_r\200\000\000\000\000\000\000\004\000'
                                                   ^^^^^ you may need to set region id properly
sql> ALTER TABLE t SET TIFLASH REPLICA 1;
```

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix adding TiFlash replica may break TiFlash in some cases
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by JaySon-Huang** [comment]
There was a similar behavior in TiSpark that cause TiFlash can not read all rows from a table https://github.com/pingcap/tispark/pull/2101

**Comment by JaySon-Huang** [comment]
Some ut are broken after disabling the check
```
[2022-12-21T10:01:21.926Z] FAILED TESTS (2/1762):
[2022-12-21T10:01:21.926Z]     1274 ms: /tiflash/gtests_dbms Group/StoreIngestTest.RangeSmallerThanData/0
[2022-12-21T10:01:21.926Z]     1371 ms: /tiflash/gtests_dbms Group/StoreIngestTest.RangeSmallerThanData/1
```

**Pull request merged**
