### PR TITLE
fix tsan fail in unit test `ConfigReloaderTest.WithConfigObject`

### LINKED ISSUE #6569: tsan run fail in unit test `ConfigReloaderTest.WithConfigObject`
## Bug Report

```
[2023-01-02T18:05:20.505Z] [0;33mNote: Google Test filter = ConfigReloaderTest.WithConfigObject
[2023-01-02T18:05:20.505Z] [m[0;32m[==========] [mRunning 1 test from 1 test case.
[2023-01-02T18:05:20.505Z] [0;32m[----------] [mGlobal test environment set-up.
[2023-01-02T18:05:20.506Z] [0;32m[----------] [m1 test from ConfigReloaderTest
[2023-01-02T18:05:20.506Z] [0;32m[ RUN      ] [mConfigReloaderTest.WithConfigObject
[2023-01-02T18:05:20.506Z] [2023/01/03 02:05:14.265 +08:00] [DEBUG] [ConfigReloader.cpp:94] ["Loading config from `/tiflash/tmp/ConfigReloaderTest_WithConfigObject`"] [source=CfgReloader] [thread_id=1]
[2023-01-02T18:05:20.506Z] [2023/01/03 02:05:16.267 +08:00] [DEBUG] [ConfigReloader.cpp:94] ["Loading config from `/tiflash/tmp/ConfigReloaderTest_WithConfigObject`"] [source=CfgReloader] [thread_id=42]
[2023-01-02T18:05:20.506Z] LLVMSymbolizer: error reading file: No such file or directory
[2023-01-02T18:05:20.506Z] ==================
[2023-01-02T18:05:20.506Z] WARNING: ThreadSanitizer: data race (pid=22074)
[2023-01-02T18:05:20.506Z]   Read of size 4 at 0x7ffff5778844 by main thread:
[2023-01-02T18:05:20.506Z]     #0 testing::AssertionResult testing::internal::CmpHelperEQ<int, int>(char const*, char const*, int const&, int const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:1444:7 (gtests_dbms+0x24207ae)
[2023-01-02T18:05:20.506Z]     #1 testing::AssertionResult testing::internal::EqHelper<false>::Compare<int, int>(char const*, char const*, int const&, int const&) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:1472:12 (gtests_dbms+0x24207ae)
[2023-01-02T18:05:20.506Z]     #2 DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/tests/gtest_config_reloader.cpp:113:5 (gtests_dbms+0x24207ae)
[2023-01-02T18:05:20.506Z]     #3 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xa8d7065)
[2023-01-02T18:05:20.506Z]     #4 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xa8d7065)
[2023-01-02T18:05:20.506Z]     #5 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xa8b0c05)
[2023-01-02T18:05:20.506Z]     #6 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xa8b2434)
[2023-01-02T18:05:20.506Z]     #7 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xa8b30fd)
[2023-01-02T18:05:20.506Z]     #8 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xa8c32b0)
[2023-01-02T18:05:20.506Z]     #9 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xa8d8505)
[2023-01-02T18:05:20.506Z]     #10 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xa8d8505)
[2023-01-02T18:05:20.506Z]     #11 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xa8c2598)
[2023-01-02T18:05:20.506Z]     #12 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x63ea389)
[2023-01-02T18:05:20.506Z]     #13 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:78:16 (gtests_dbms+0x63ea389)
[2023-01-02T18:05:20.506Z] 
[2023-01-02T18:05:20.506Z]   Previous write of size 4 at 0x7ffff5778844 by thread T46 (mutexes: write M177746173572940360):
[2023-01-02T18:05:20.506Z]     #0 DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2::operator()(Poco::AutoPtr<Poco::Util::AbstractConfiguration>) const /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/tests/gtest_config_reloader.cpp:107:23 (gtests_dbms+0x24210e7)
[2023-01-02T18:05:20.507Z]     #1 decltype(static_cast<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2&>(fp)(static_cast<Poco::AutoPtr<Poco::Util::AbstractConfiguration>>(fp0))) std::__1::__invoke<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2&, Poco::AutoPtr<Poco::Util::AbstractConfiguration> >(DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2&, Poco::AutoPtr<Poco::Util::AbstractConfiguration>&&) /usr/local/bin/../include/c++/v1/type_traits:3918:1 (gtests_dbms+0x24210e7)
[2023-01-02T18:05:20.507Z]     #2 void std::__1::__invoke_void_return_wrapper<void, true>::__call<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2&, Poco::AutoPtr<Poco::Util::AbstractConfiguration> >(DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2&, Poco::AutoPtr<Poco::Util::AbstractConfiguration>&&) /usr/local/bin/../include/c++/v1/__functional/invoke.h:61:9 (gtests_dbms+0x24210e7)
[2023-01-02T18:05:20.507Z]     #3 std::__1::__function::__alloc_func<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2, std::__1::allocator<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2>, void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>)>::operator()(Poco::AutoPtr<Poco::Util::AbstractConfiguration>&&) /usr/local/bin/../include/c++/v1/__functional/function.h:171:16 (gtests_dbms+0x24210e7)
[2023-01-02T18:05:20.507Z]     #4 std::__1::__function::__func<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2, std::__1::allocator<DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody()::$_2>, void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>)>::operator()(Poco::AutoPtr<Poco::Util::AbstractConfiguration>&&) /usr/local/bin/../include/c++/v1/__functional/function.h:345:12 (gtests_dbms+0x24210e7)
[2023-01-02T18:05:20.507Z]     #5 std::__1::__function::__value_func<void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>)>::operator()(Poco::AutoPtr<Poco::Util::AbstractConfiguration>&&) const /usr/local/bin/../include/c++/v1/__functional/function.h:498:16 (gtests_dbms+0xd39a086)
[2023-01-02T18:05:20.507Z]     #6 std::__1::function<void (Poco::AutoPtr<Poco::Util::AbstractConfiguration>)>::operator()(Poco::AutoPtr<Poco::Util::AbstractConfiguration>) const /usr/local/bin/../include/c++/v1/__functional/function.h:1175:12 (gtests_dbms+0xd39a086)
[2023-01-02T18:05:20.507Z]     #7 DB::ConfigReloader::reloadIfNewer(bool, bool) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/Config/ConfigReloader.cpp:118:13 (gtests_dbms+0xd39a086)
[2023-01-02T18:05:20.507Z]     #8 DB::ConfigReloader::run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/Config/ConfigReloader.cpp:69:9 (gtests_dbms+0xd39a53b)
[2023-01-02T18:05:20.507Z]     #9 decltype(*(static_cast<DB::ConfigReloader*>(fp0)).*fp()) std::__1::__invoke<void (DB::ConfigReloader::*)(), DB::ConfigReloader*, void>(void (DB::ConfigReloader::*&&)(), DB::ConfigReloader*&&) /usr/local/bin/../include/c++/v1/type_traits:3859:1 (gtests_dbms+0xd39ac23)
[2023-01-02T18:05:20.507Z]     #10 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::ConfigReloader::*)(), DB::ConfigReloader*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::ConfigReloader::*)(), DB::ConfigReloader*>&, std::__1::__tuple_indices<2ul>) /usr/local/bin/../include/c++/v1/thread:280:5 (gtests_dbms+0xd39ac23)
[2023-01-02T18:05:20.507Z]     #11 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (DB::ConfigReloader::*)(), DB::ConfigReloader*> >(void*) /usr/local/bin/../include/c++/v1/thread:291:5 (gtests_dbms+0xd39ac23)
[2023-01-02T18:05:20.507Z] 
[2023-01-02T18:05:20.507Z]   As if synchronized via sleep:
[2023-01-02T18:05:20.507Z]     #0 nanosleep /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:363:3 (gtests_dbms+0x2366e2f)
[2023-01-02T18:05:20.507Z]     #1 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) <null> (libc++.so.1+0x709ba)
[2023-01-02T18:05:20.507Z]     #2 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xa8d7065)
[2023-01-02T18:05:20.508Z]     #3 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xa8d7065)
[2023-01-02T18:05:20.508Z]     #4 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xa8b0c05)
[2023-01-02T18:05:20.508Z]     #5 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xa8b2434)
[2023-01-02T18:05:20.508Z]     #6 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xa8b30fd)
[2023-01-02T18:05:20.508Z]     #7 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xa8c32b0)
[2023-01-02T18:05:20.508Z]     #8 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xa8d8505)
[2023-01-02T18:05:20.508Z]     #9 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xa8d8505)
[2023-01-02T18:05:20.508Z]     #10 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xa8c2598)
[2023-01-02T18:05:20.508Z]     #11 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x63ea389)
[2023-01-02T18:05:20.508Z]     #12 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:78:16 (gtests_dbms+0x63ea389)
[2023-01-02T18:05:20.508Z] 
[2023-01-02T18:05:20.508Z]   Location is stack of main thread.
[2023-01-02T18:05:20.508Z] 
[2023-01-02T18:05:20.508Z]   Location is global '??' at 0x7ffff5759000 ([stack]+0x00000001f844)
[2023-01-02T18:05:20.508Z] 
[2023-01-02T18:05:20.508Z]   Mutex M177746173572940360 is already destroyed.
[2023-01-02T18:05:20.508Z] 
[2023-01-02T18:05:20.508Z]   Thread T46 'CfgReloader' (tid=22353, running) created by main thread at:
[2023-01-02T18:05:20.508Z]     #0 pthread_create /llvm-project/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp:977:3 (gtests_dbms+0x23694bd)
[2023-01-02T18:05:20.508Z]     #1 std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /usr/local/bin/../include/c++/v1/__threading_support:514:10 (gtests_dbms+0xd39aa35)
[2023-01-02T18:05:20.508Z]     #2 std::__1::thread::thread<void (DB::ConfigReloader::*)(), DB::ConfigReloader*, void>(void (DB::ConfigReloader::*&&)(), DB::ConfigReloader*&&) /usr/local/bin/../include/c++/v1/thread:307:16 (gtests_dbms+0xd39aa35)
[2023-01-02T18:05:20.508Z]     #3 DB::ConfigReloader::start() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/Config/ConfigReloader.cpp:40:14 (gtests_dbms+0xd39a469)
[2023-01-02T18:05:20.508Z]     #4 DB::tests::ConfigReloaderTest_WithConfigObject_Test::TestBody() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/Common/tests/gtest_config_reloader.cpp:111:27 (gtests_dbms+0x2420783)
[2023-01-02T18:05:20.508Z]     #5 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xa8d7065)
[2023-01-02T18:05:20.508Z]     #6 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xa8d7065)
[2023-01-02T18:05:20.508Z]     #7 testing::Test::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2517:5 (gtests_dbms+0xa8b0c05)
[2023-01-02T18:05:20.508Z]     #8 testing::TestInfo::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2693:11 (gtests_dbms+0xa8b2434)
[2023-01-02T18:05:20.508Z]     #9 testing::TestCase::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2811:28 (gtests_dbms+0xa8b30fd)
[2023-01-02T18:05:20.509Z]     #10 testing::internal::UnitTestImpl::RunAllTests() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:5177:43 (gtests_dbms+0xa8c32b0)
[2023-01-02T18:05:20.509Z]     #11 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2443:10 (gtests_dbms+0xa8d8505)
[2023-01-02T18:05:20.509Z]     #12 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:2479:14 (gtests_dbms+0xa8d8505)
[2023-01-02T18:05:20.509Z]     #13 testing::UnitTest::Run() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/src/gtest.cc:4786:10 (gtests_dbms+0xa8c2598)
[2023-01-02T18:05:20.509Z]     #14 RUN_ALL_TESTS() /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:2341:46 (gtests_dbms+0x63ea389)
[2023-01-02T18:05:20.509Z]     #15 main /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/dbms/src/TestUtils/gtests_dbms_main.cpp:78:16 (gtests_dbms+0x63ea389)
[2023-01-02T18:05:20.509Z] 
[2023-01-02T18:05:20.509Z] SUMMARY: ThreadSanitizer: data race /home/jenkins/agent/workspace/tiflash-sanitizer-daily/tiflash/contrib/googletest/googletest/include/gtest/gtest.h:1444:7 in testing::AssertionResult testing::internal::CmpHelperEQ<int, int>(char const*, char const*, int const&, int const&)
[2023-01-02T18:05:20.509Z] ==================
[2023-01-02T18:05:20.509Z] [0;32m[       OK ] [mConfigReloaderTest.WithConfigObject (4023 ms)
[2023-01-02T18:05:20.509Z] [0;32m[----------] [m1 test from ConfigReloaderTest (4023 ms total)
[2023-01-02T18:05:20.509Z] 
[2023-01-02T18:05:20.509Z] [0;32m[----------] [mGlobal test environment tear-down
[2023-01-02T18:05:20.509Z] [0;32m[==========] [m1 test from 1 test case ran. (4023 ms total)
[2023-01-02T18:05:20.509Z] [0;32m[  PASSED  ] [m1 test.
```

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: close #6569

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by SeaRise** [comment]
> /run-sanitizer-test tsan

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-sanitizer/detail/tiflash-ghpr-sanitizer/73/pipeline

**Comment by SeaRise** [comment]
> > /run-sanitizer-test tsan
> 
> https://ci.pingcap.net/blue/organizations/jenkins/tiflash-ghpr-sanitizer/detail/tiflash-ghpr-sanitizer/73/pipeline

https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/783/pipeline
`ConfigReloaderTest.WithConfigObject` has been fixed.

**Review by ywqzzy — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
