### PR TITLE
storage: fix block rows not match when filter column is the first non-empty column in the block

### LINKED ISSUE #9472: query count(*) failed
A table stored in TiFlash, using this query sometimes works, sometimes not.
image
image

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #9472

Problem Summary:

### What is changed and how it works?

Try to fix #9472, failed to reproduce the issue. But when the filter column is the first non-empty column in the block, block.rows() = filter_column->size(), but filter_column is not filtered, so the rows may not match.

**But filter_column is usually added to the back of the block, so it is kind of weird.**

```commit-message
storage: fix block rows not match when filter column is the first non-empty column in the block
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]
lgtm

**Comment by Lloyd-Pottiger** [comment]
fullstack-test2/ddl/rename_table_across_databases.test

**Pull request merged**
