### PR TITLE
rename `tidb_enable_tiflash_pipeline_model` to `tiflash_enable_pipeline_model`

### PR DESCRIPTION
**Pull request by SeaRise**
### What problem does this PR solve?

Issue Number: ref #6518
related https://github.com/pingcap/tidb/pull/46709

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by gengliqi — APPROVED** [review]
LGTM

**Comment by SeaRise** [comment]
hold until tidb ci image updated.

**Pull request merged**
