### PR TITLE
update TiFlash proxy to raftstore-proxy-6.0 for up(down)grade test

### PR DESCRIPTION
**Pull request by CalvinNeo**
Signed-off-by: CalvinNeo <calvinneo1995@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4618

Problem Summary:

Though we have already passed all test cases, we still have to check whether there are problems when TiFlash is updated from any versions to versions using proxy 6.0, before we merge PR https://github.com/pingcap/tidb-engine-ext/pull/55.

As the automated procedure to do this needs new proxy be used by TiFlash at master branch, so we have this PR. 

After this test is completed, we will then merge proxy's PR to the main branch, thus redirect TiFlash's proxy to main branch.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by solotzg — APPROVED** [review]

**Review by jiaqizho — APPROVED** [review]

**Comment by breeswish** [comment]
In my M1 Pro I experienced compiling error since this PR:

```
= note: ld: warning: directory not found for option '-L/Users/breezewish/Work/tiflash/contrib/tiflash-proxy/target/debug/build/libz-sys-981451fd99e28b0e/out/build'
          Undefined symbols for architecture arm64:
            "_SSL_get_peer_certificate", referenced from:
                ssl_handshaker_result_extract_peer(tsi_handshaker_result const*, tsi_peer*) in libgrpcio_sys-57002017520551a2.rlib(ssl_transport_security.cc.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

However I can compile successfully in TiKV master branch. Do you have any ideas?

**Pull request merged**
