### PR TITLE
Fix DeltaMergeHelpers.cpp clang tidy.

### LINKED ISSUE #4602: Fix clang-tidy error in `dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp`
## Enhancement
```shell
clang-tidy -p=/home/finder/projects/tiflash/build/ /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp
/home/finder/projects/tiflash/contrib/boost/boost/config/detail/select_stdlib_config.hpp:26:14: error: 'cstddef' file not found [clang-diagnostic-error]
#    include <cstddef>
             ^
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp:22:67: error: parameter 'to_type' is unused [misc-unused-parameters,-warnings-as-errors]
void convertColumn(Block & block, size_t pos, const DataTypePtr & to_type, const Context & context)
                                                                  ^~~~~~~
                                                                   /*to_type*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp:46:51: error: parameter 'Container' is unused [misc-unused-parameters,-warnings-as-errors]
void appendIntoHandleColumn(ColumnVector<Handle>::Container & handle_column, const DataTypePtr & type, const ColumnPtr & data)
                                                  ^~~~~~~~~
                                                   /*Container*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp:54:30: error: macro argument should be enclosed in parentheses [bugprone-macro-parentheses,-warnings-as-errors]
        handle_column[i] <<= SHIFT;                \
                             ^
                             (    )
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp:55:29: error: macro argument should be enclosed in parentheses [bugprone-macro-parentheses,-warnings-as-errors]
        handle_column[i] |= MARK & DATA_VECTOR[i]; \
                            ^
                            (   )
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp:55:36: error: macro argument should be enclosed in parentheses [bugprone-macro-parentheses,-warnings-as-errors]
        handle_column[i] |= MARK & DATA_VECTOR[i]; \
                                   ^
                                   (          )
46033 warnings and 1 error generated.
Error while processing /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp.
Suppressed 46046 warnings (46028 in non-user code, 18 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
5 warnings treated as errors
```

### PR DESCRIPTION
**Pull request by cakebytheoceanLuo**
Signed-off-by: Jigao Luo <luojigao@outlook.com>

### What problem does this PR solve?

Issue Number: close #4602 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
@cakebytheoceanLuo Thanks for your contribution! Could you please run the format script locally refer to https://github.com/pingcap/tiflash#contributing

**Comment by cakebytheoceanLuo** [comment]
> @cakebytheoceanLuo Thanks for your contribution! Could you please run the format script locally refer to https://github.com/pingcap/tiflash#contributing

The output is followings:
```
python3 format-diff.py --diff_from `git merge-base origin/master HEAD`
Files to format:
  /home/jigao/Workspace/tiflash/dbms/src/Storages/DeltaMerge/DeltaMergeHelpers.cpp
Finish code format
```
Does it mean an error?

**Comment by Lloyd-Pottiger** [comment]
> Does it mean an error?

no, it is expected output.

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
