### PR TITLE
fix typo

### LINKED ISSUE #4672: some typo under `dbms/src/Storages/Page`
## Enhancement
e.g.
https://github.com/pingcap/tiflash/blob/989bf8db36e73493ab9e9c780fca9cc77af0fa88/dbms/src/Storages/Page/PageStorage.h#L65

### PR DESCRIPTION
**Pull request by nautaa**
### What problem does this PR solve?

Issue Number: close #4672 

Problem Summary: fix typo.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [x] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
@nautaa Thanks for your participation and contribution! Could you please open an issue about it and link this PR to it?
```
What problem does this PR solve?
Issue Number: close#xxx
```

**Review by Lloyd-Pottiger — APPROVED** [review]
LGTM

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Pull request merged**
