### PR TITLE
PageStorage: Fix TiFlash may fail to restart after FAP is enabled

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/9307

Problem Summary: 

A RemotePage
1. Ingested into a Segment by FAP
2. The Segment get logical split, two RefPage to the RemotePage is created
3. The Ingested RemotePage is deleted
4. The split left and right segment get logical split again
5. A read to the segment is performed, and the original RemotePage get updated

The sequence that PageStorage see is
```
--- The page_id '0x78000001746C0000000000000060.3359'
---  created @ ver=676072, epoch=0
---  ref by .3439 @ ver=685132
---  ref by .3441 @ ver=685134
---  deleted @ ver=685265
---  ref by .3493 @ ver=693249
---  ref by .3495 @ ver=693251
---  ref by .3497 @ ver=693272
---  ref by .3499 @ ver=693274
--- Then '.3497' get read, UPDATE_DATA_FROM_REMOTE @ ver=729397
```

### What is changed and how it works?

```commit-message
PageStorage: Fix TiFlash may fail to restart after FAP is enabled
```

`PageDirectory::updateLocalCacheForRemotePages` and `PageDirectoryFactory::applyRecord` will call `updateLocalCacheForRemotePage` with ignore_delete=true when trying to update local cache of a RefPage (`id_to_resolve != r.page_id`)

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]
lgtm

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by JaySon-Huang** [comment]
```
FAILED TESTS (2/2850):
    6710 ms: /tiflash/gtests_dbms ReadIndexTest.workers
  231116 ms: /tiflash/gtests_dbms ComputeServerRunner.multipleQuery
INTERRUPTED TESTS (1/2850):
Interrupted: /tiflash/gtests_dbms RegionKVStoreTestFAP.TableNotFound
```
after running for 45min

**Pull request merged**
