### PR TITLE
[DNM] S3 bench

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by JaySon-Huang** [comment]
http://fileserver.pingcap.net/download/builds/pingcap/test/tiflash/master/c8a2c363b82ffd236fa68e3e6bc73a387523658e/centos7/tiflash-linux-arm64.tar.gz

**Pull request closed without merging**
