### PR TITLE
ddl: Fix the storage instance may be physically dropped when the region is not removed

### PR DESCRIPTION
**Pull request by JaySon-Huang**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/8710

Problem Summary:
There are some case that a region may not be removed from TiFlash when there are unhealth peers. However, after the tiflash replica is set to zero, the data still be physically dropped after gc safepoint exceed.

### What is changed and how it works?

* Prevent the storage instance being physically dropped when the region is not removed
* Throw exception when the storage instance is not exist after schema synced

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the issue that the tiflash replica data may be corrupted after setting the tiflash replica to 0 and add it back later
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by hongyunyan — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
This PR also prevent data being unexpected dropped when the region is not removed like https://github.com/pingcap/tiflash/issues/8777

**Pull request merged**
