### PR TITLE
cmake: Use gnu objcopy by default

### PR DESCRIPTION
**Pull request by breezewish**
Signed-off-by: Wish <breezewish@outlook.com>

### What problem does this PR solve?

Issue Number: ref #5985

Problem Summary:

### What is changed and how it works?

In https://github.com/pingcap/tiflash/issues/5985 we changed to store compressed DWARF in the new standard gABI format. However binutils in CentOS 7 does not recognize this format, so this PR brings back the old format.

The support for the old format has been removed in LLVM 15, so we just use the GNU objcopy to do this job.

Note: Go 1.19 changed to use the new standard gABI format as well: https://github.com/golang/go/commit/d151134851554aa0a3f05206019b9b8c1e1ad70f

More references: https://maskray.me/blog/2022-01-23-compressed-debug-sections

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)

  ```shell
  objdump -x ./tiflash  # Works fine
  ```

  In CI we have the GNU objdump: https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/14951/pipeline/163

- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]
maybe we should abandon centos7……

**Comment by breezewish** [comment]
> maybe we should abandon centos7……

Unfortunately CentOS 7 has not EOL yet.. But soon!

**Comment by breezewish** [comment]
Update:

I have verified that, when using the gABI format, binutils in CentOS 7 doesn't work (e.g. objdump), but the Linux perf still works. So there are actually fewer blocking stones for us to deprecate the legacy format.

**Pull request merged**
