### PR TITLE
Enhancement: Add how to run integration tests and microbenchmark tests in README

### LINKED ISSUE #5172: How to run integration test locally?
## General Question
Newcomer might run across this question.
We need a doc to demonstrate the way to run integration test.

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close #5172 #5178 

Problem Summary:

### What is changed and how it works?

Add how to run integration tests and microbenchmark tests in README

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hongyunyan** [comment]
cc @JaySon-Huang

**Review by SchrodingerZhu — APPROVED** [review]

**Review by lidezhu — APPROVED** [review]

**Pull request merged**
