### PR TITLE
Add RFC for 'Reduce the number of files used by TiFlash'

### PR DESCRIPTION
**Pull request by hongyunyan**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/7595

Problem Summary:

### What is changed and how it works?

Add RFC for 'Reduce the number of files used by TiFlash'

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hongyunyan** [comment]
@flowbehappy

**Comment by hongyunyan** [comment]
cc @flowbehappy

**Review by flowbehappy — APPROVED** [review]

**Pull request merged**
