### PR TITLE
fix empty segment cannot merge after gc

### PR DESCRIPTION
**Pull request by lidezhu**
This is an cherry-pick of #4500

### What problem does this PR solve?

Issue Number: close #4511

Problem Summary:
1. empty segments cannot be merged after gc;
2. when a segment can be triggerred to gc because of too many delete range, we still wait for the gc_safe_point change, which is not needed.

### What is changed and how it works?
1. when segment should be gced because of too many delete range, do it regardless of the gc_safe_point;
2. only update index cache for read thread;
3. fix unstable rough set filter test because of more fast gc speed.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. load data into tiflash and check segment status;
image
4. set tiflash replica to 0 and check segment status after a while
image

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
Fix the problem that empty segments cannot be merged after gc
```

### CODE REVIEW

**Comment by lidezhu** [comment]
@JaySon-Huang PTAL

**Review by JaySon-Huang — APPROVED** [review]

**Pull request merged**
