### PR TITLE
Remove invalid blob file after BlobStore restored.

### PR DESCRIPTION
**Pull request by jiaqizho**
### What problem does this PR solve?

Issue Number: ref #3594 

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lidezhu — APPROVED** [review]
LGTM

**Comment by JaySon-Huang** [comment]
/hold

@jiaqizho PTAL

```
[2022-04-01T07:18:09.424Z] [521/1123] BlobStoreTest.Restore (865 ms)
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.852 +08:00] [INFO] [PathCapacityMetrics.cpp:84] ["PathCapacityMetrics:Init capacity [path=/home/jenkins/agent/workspace/tiflash-ghpr-unit-tests/tiflash/tmp/] [capacity=0.00 B]"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.852 +08:00] [INFO] [MinTSOScheduler.cpp:47] ["MinTSOScheduler:thread_hard_limit is 10000, thread_soft_limit is 5000, and active_set_soft_limit is 11 in MinTSOScheduler."] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.853 +08:00] [INFO] [RegionPersister.cpp:196] ["RegionPersister:RegionPersister running in v2 mode"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.853 +08:00] [INFO] [PageStorage.cpp:200] ["PageStorage:RegionPersister begin to restore data from disk. [path=/home/jenkins/agent/workspace/tiflash-ghpr-unit-tests/tiflash/tmp/kvstore] [num_writers=4]"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [PageStorage.cpp:354] ["PageStorage:RegionPersister restore 0 pages, write batch sequence: 0, 0 puts and 0 refs and 0 deletes and 0 upserts"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [KVStore.cpp:59] ["KVStore:Restored 0 regions"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [RegionTable.cpp:182] ["RegionTable:Start to restore"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [RegionTable.cpp:188] ["RegionTable:Restore 0 tables"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [0;33mNote: Google Test filter = BlobStoreTest.Restore
[2022-04-01T07:18:09.424Z] [m[0;32m[==========] [mRunning 1 test from 1 test case.
[2022-04-01T07:18:09.424Z] [0;32m[----------] [mGlobal test environment set-up.
[2022-04-01T07:18:09.424Z] [0;32m[----------] [m1 test from BlobStoreTest
[2022-04-01T07:18:09.424Z] [0;32m[ RUN      ] [mBlobStoreTest.Restore
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.890 +08:00] [DEBUG] [BlobStore.cpp:992] ["BlobStore:Created a new BlobStat [blob_id=10]"] [thread_id=1]
[2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.890 +08:00] [DEBUG] [BlobStore.cpp:992] ["BlobStore:Created a new BlobStat [blob_id=12]"] [thread_id=1]
[2022-04-01T07:18:09.424Z] Code: 49. DB::Exception: Some of Blob are missing in disk.[path=/home/jenkins/agent/workspace/tiflash-ghpr-unit-tests/tiflash/tmp/BlobStoreTest.Restore] [stats ids: 10, 12]
[2022-04-01T07:18:09.424Z] 
[2022-04-01T07:18:09.424Z] Stack trace:
[2022-04-01T07:18:09.424Z] 
[2022-04-01T07:18:09.424Z]       0x1361c090	StackTrace::StackTrace() [gtests_dbms+325173392]
[2022-04-01T07:18:09.424Z]        0x6f59544	DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+116757828]
[2022-04-01T07:18:09.424Z]       0x125fa509	DB::PS::V3::BlobStore::BlobStats::restore() [gtests_dbms+308258057]
[2022-04-01T07:18:09.424Z]        0x896bd6c	DB::PS::V3::tests::BlobStoreTest_Restore_Test::TestBody() [gtests_dbms+144096620]
[2022-04-01T07:18:09.424Z]       0x1032d84d	void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+271767629]
[2022-04-01T07:18:09.424Z]       0x10315210	void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+271667728]
[2022-04-01T07:18:09.424Z]       0x102f9d76	testing::Test::Run() [gtests_dbms+271555958]
[2022-04-01T07:18:09.425Z]       0x102faa09	testing::TestInfo::Run() [gtests_dbms+271559177]
[2022-04-01T07:18:09.425Z]       0x102fb09f	testing::TestCase::Run() [gtests_dbms+271560863]
[2022-04-01T07:18:09.425Z]       0x10303185	testing::internal::UnitTestImpl::RunAllTests() [gtests_dbms+271593861]
[2022-04-01T07:18:09.425Z]       0x103324bd	bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+271787197]
[2022-04-01T07:18:09.425Z]       0x10317bb0	bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+271678384]
[2022-04-01T07:18:09.425Z]       0x10302c9e	testing::UnitTest::Run() [gtests_dbms+271592606]
[2022-04-01T07:18:09.425Z]        0x8c6fa73	RUN_ALL_TESTS() [gtests_dbms+147257971]
[2022-04-01T07:18:09.425Z]        0x8c6d7ad	main [gtests_dbms+147249069]
[2022-04-01T07:18:09.425Z]   0x7f861de16555	__libc_start_main [libc.so.6+140629]
[2022-04-01T07:18:09.425Z]        0x6f4d729	<unknown symbol> [gtests_dbms+116709161]
[2022-04-01T07:18:09.425Z] unknown file: Failure
[2022-04-01T07:18:09.425Z] C++ exception with description "DB::Exception" thrown in the test body.
[2022-04-01T07:18:09.425Z] [0;31m[  FAILED  ] [mBlobStoreTest.Restore (222 ms)
[2022-04-01T07:18:09.425Z] [0;32m[----------] [m1 test from BlobStoreTest (222 ms total)
[2022-04-01T07:18:09.425Z] 
[2022-04-01T07:18:09.425Z] [0;32m[----------] [mGlobal test environment tear-down
[2022-04-01T07:18:09.425Z] [0;32m[==========] [m1 test from 1 test case ran. (222 ms total)
[2022-04-01T07:18:09.425Z] [0;32m[  PASSED  ] [m0 tests.
[2022-04-01T07:18:09.425Z] [0;31m[  FAILED  ] [m1 test, listed below:
[2022-04-01T07:18:09.425Z] [0;31m[  FAILED  ] [mBlobStoreTest.Restore
[2022-04-01T07:18:09.425Z] 
[2022-04-01T07:18:09.425Z]  1 FAILED TEST
```

**Comment by jiaqizho** [comment]
> /hold
> 
> @jiaqizho PTAL
> 
> ```
> [2022-04-01T07:18:09.424Z] [521/1123] BlobStoreTest.Restore (865 ms)
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.852 +08:00] [INFO] [PathCapacityMetrics.cpp:84] ["PathCapacityMetrics:Init capacity [path=/home/jenkins/agent/workspace/tiflash-ghpr-unit-tests/tiflash/tmp/] [capacity=0.00 B]"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.852 +08:00] [INFO] [MinTSOScheduler.cpp:47] ["MinTSOScheduler:thread_hard_limit is 10000, thread_soft_limit is 5000, and active_set_soft_limit is 11 in MinTSOScheduler."] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.853 +08:00] [INFO] [RegionPersister.cpp:196] ["RegionPersister:RegionPersister running in v2 mode"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.853 +08:00] [INFO] [PageStorage.cpp:200] ["PageStorage:RegionPersister begin to restore data from disk. [path=/home/jenkins/agent/workspace/tiflash-ghpr-unit-tests/tiflash/tmp/kvstore] [num_writers=4]"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [PageStorage.cpp:354] ["PageStorage:RegionPersister restore 0 pages, write batch sequence: 0, 0 puts and 0 refs and 0 deletes and 0 upserts"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [KVStore.cpp:59] ["KVStore:Restored 0 regions"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [RegionTable.cpp:182] ["RegionTable:Start to restore"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.855 +08:00] [INFO] [RegionTable.cpp:188] ["RegionTable:Restore 0 tables"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] �[0;33mNote: Google Test filter = BlobStoreTest.Restore
> [2022-04-01T07:18:09.424Z] �[m�[0;32m[==========] �[mRunning 1 test from 1 test case.
> [2022-04-01T07:18:09.424Z] �[0;32m[----------] �[mGlobal test environment set-up.
> [2022-04-01T07:18:09.424Z] �[0;32m[----------] �[m1 test from BlobStoreTest
> [2022-04-01T07:18:09.424Z] �[0;32m[ RUN      ] �[mBlobStoreTest.Restore
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.890 +08:00] [DEBUG] [BlobStore.cpp:992] ["BlobStore:Created a new BlobStat [blob_id=10]"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] [2022/04/01 15:18:08.890 +08:00] [DEBUG] [BlobStore.cpp:992] ["BlobStore:Created a new BlobStat [blob_id=12]"] [thread_id=1]
> [2022-04-01T07:18:09.424Z] Code: 49. DB::Exception: Some of Blob are missing in disk.[path=/home/jenkins/agent/workspace/tiflash-ghpr-unit-tests/tiflash/tmp/BlobStoreTest.Restore] [stats ids: 10, 12]
> [2022-04-01T07:18:09.424Z] 
> [2022-04-01T07:18:09.424Z] Stack trace:
> [2022-04-01T07:18:09.424Z] 
> [2022-04-01T07:18:09.424Z]       0x1361c090	StackTrace::StackTrace() [gtests_dbms+325173392]
> [2022-04-01T07:18:09.424Z]        0x6f59544	DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) [gtests_dbms+116757828]
> [2022-04-01T07:18:09.424Z]       0x125fa509	DB::PS::V3::BlobStore::BlobStats::restore() [gtests_dbms+308258057]
> [2022-04-01T07:18:09.424Z]        0x896bd6c	DB::PS::V3::tests::BlobStoreTest_Restore_Test::TestBody() [gtests_dbms+144096620]
> [2022-04-01T07:18:09.424Z]       0x1032d84d	void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+271767629]
> [2022-04-01T07:18:09.424Z]       0x10315210	void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [gtests_dbms+271667728]
> [2022-04-01T07:18:09.424Z]       0x102f9d76	testing::Test::Run() [gtests_dbms+271555958]
> [2022-04-01T07:18:09.425Z]       0x102faa09	testing::TestInfo::Run() [gtests_dbms+271559177]
> [2022-04-01T07:18:09.425Z]       0x102fb09f	testing::TestCase::Run() [gtests_dbms+271560863]
> [2022-04-01T07:18:09.425Z]       0x10303185	testing::internal::UnitTestImpl::RunAllTests() [gtests_dbms+271593861]
> [2022-04-01T07:18:09.425Z]       0x103324bd	bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+271787197]
> [2022-04-01T07:18:09.425Z]       0x10317bb0	bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) [gtests_dbms+271678384]
> [2022-04-01T07:18:09.425Z]       0x10302c9e	testing::UnitTest::Run() [gtests_dbms+271592606]
> [2022-04-01T07:18:09.425Z]        0x8c6fa73	RUN_ALL_TESTS() [gtests_dbms+147257971]
> [2022-04-01T07:18:09.425Z]        0x8c6d7ad	main [gtests_dbms+147249069]
> [2022-04-01T07:18:09.425Z]   0x7f861de16555	__libc_start_main [libc.so.6+140629]
> [2022-04-01T07:18:09.425Z]        0x6f4d729	<unknown symbol> [gtests_dbms+116709161]
> [2022-04-01T07:18:09.425Z] unknown file: Failure
> [2022-04-01T07:18:09.425Z] C++ exception with description "DB::Exception" thrown in the test body.
> [2022-04-01T07:18:09.425Z] �[0;31m[  FAILED  ] �[mBlobStoreTest.Restore (222 ms)
> [2022-04-01T07:18:09.425Z] �[0;32m[----------] �[m1 test from BlobStoreTest (222 ms total)
> [2022-04-01T07:18:09.425Z] 
> [2022-04-01T07:18:09.425Z] �[0;32m[----------] �[mGlobal test environment tear-down
> [2022-04-01T07:18:09.425Z] �[0;32m[==========] �[m1 test from 1 test case ran. (222 ms total)
> [2022-04-01T07:18:09.425Z] �[0;32m[  PASSED  ] �[m0 tests.
> [2022-04-01T07:18:09.425Z] �[0;31m[  FAILED  ] �[m1 test, listed below:
> [2022-04-01T07:18:09.425Z] �[0;31m[  FAILED  ] �[mBlobStoreTest.Restore
> [2022-04-01T07:18:09.425Z] 
> [2022-04-01T07:18:09.425Z]  1 FAILED TEST
> ```

Waiting for `GitHub reroute`.

**Pull request merged**
