### PR TITLE
Improve metrics for BR import

### PR DESCRIPTION
**Pull request by breezewish**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/7245

Problem Summary:

### What is changed and how it works?

1. Removed the upper limit line of SST importer thread, because it is wrong.

2. Introduce IO Throughput panel. This is very useful as in cloud environment it is hard to learn the node-level metrics. 

   It is counted as:

   ```
   sum by (instance) (irate(tiflash_proxy_threads_io_bytes_total{...}[1m]))
   ```

   image

   Unfortunately seems that there is no easy way for us to learn iops.

3. Adjusted several other panels.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by CalvinNeo — APPROVED** [review]
lgtm

**Comment by JaySon-Huang** [comment]
1. Maybe keep the "Opened File Count" panel? It helped us find out serval file handle leak problems.
2. Put "I/O Limiter" and "I/O Limiter Pending Tasks" in the same row is better
image
3. Move "Schema of Column File" up and let the S3 related panels placed together (or maybe we need a new group of S3 related metrics)
image

**Review by hongyunyan — APPROVED** [review]

**Comment by breezewish** [comment]
> * ~Maybe keep the "Opened File Count" panel? It helped us find out serval file handle leak problems.~ Oh I see it is moved into "Storages"
> * Put "I/O Limiter" and "I/O Limiter Pending Tasks" in the same row is better
>   image
> * Move "Schema of Column File" up and let the S3 related panels placed together (or maybe we need a new group of S3 related metrics)
>   image

Now S3 metrics are moved to the "Disaggregated" row.

**Comment by JaySon-Huang** [comment]
@breezewish should we backport the "IO Throughput panel" to release-6.1 and release-6.4 branch?

**Pull request merged**
