### PR TITLE
optimize memory usage of lock cf

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: ref #4728 

Problem Summary: For lock cf, we store both it's `TiKVValue` for serialization and `DecodedLockCFValue` for lock resolve which is redundant and consume a lot of memory.

### What is changed and how it works?
Avoid store TiKVValue for lock cf and generating it on the fly.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
1. load tpch50;
2. run `2. update lineitem set L_SUPPKEY=100000 limit 50000000;`

Before optimize:
image
After optimize:
image
The memory consumption peak decreases about 10GB.

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by flowbehappy — APPROVED** [review]

**Comment by lidezhu** [comment]
The short value in lock cf may be used when adapting to cloud engine. So this optimization may be not applicable.

**Pull request closed without merging**
