### PR TITLE
Add fail point pause_after_copr_streams_acquired_once

### LINKED ISSUE #4868: Add a fail point to pause one of query thread
## Enhancement
Add a `pause_after_copr_streams_acquired_once to pause` one of query thread. This will help the storage layer to generate a very long stale snapshot.
Diff with `pause_after_copr_streams_acquired`, `pause_after_copr_streams_acquired` will pause channel of query, but `pause_after_copr_streams_acquired_once` will pause once.

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: close #4868

Problem Summary:

### What is changed and how it works?
Add fail point `pause_after_copr_streams_acquired_once` which is the same as `pause_after_copr_streams_acquired` but only fail once.
### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by jiaqizho** [comment]
@SeaRise  
Not sure why `pause_after_copr_streams_acquired` removed. But @Lloyd-Pottiger added a `pause_after_copr_streams_acquired_once` to pause one of query thread. This will help the storage layer to generate a very long stale snapshot. is that make sense to you ?

**Review by SeaRise — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Pull request merged**
