### PR TITLE
update client-c to fix region not balance for tiflash_compute node

### LINKED ISSUE #6916: region is not balance when dispatches to tiflash_storage nodes for static pruning partition table.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. We use very big internal dataset(ask me for mysql link if you want to reproduce). (topo is: two `tiflash_compute nodes` and two `tiflash_storage nodes`
2. run following sqls:
```
set @@tidb_partition_prune_mode = 'static';
select count(*) from xxx_events;
```
3. check logs for two tiflash_compute nodes.
<!-- a step by step guide for reproducing the bug. -->

### 2. What did you expect to see? (Required)
region should balance.
### 3. What did you see instead (Required)
regoin is not balace. We can see there is two aspects of not balancing:
1. same tiflash_compute dispatch to two tiflash_storage nodes is not balance(395 VS 1148, 1768 VS 4900). (Workround is here: https://github.com/pingcap/tidb/pull/41406)
2. regsion need to read between two tiflash_compute nodes.(395+1148=1543 VS 1768+4900=6668)
```
tiflash_compute-0 -> tiflash_storage-0: 395
tiflash_compute-0 -> tiflash_storage-1: 1148
tiflash_compute-0 -> tiflash_storage-0: 1768
tiflash_compute-1 -> tiflash_storage-1: 4900
```
### 4. What is your TiFlash version? (Required)
```
MySQL [test]> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                         |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.7.0-alpha-111-gb417ad0689
Edition: Community
Git Commit Hash: b417ad0689795a265df9cdba22c40871f50b7e55
Git Branch: master
UTC Build Time: 2023-02-28 08:35:54
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

### PR DESCRIPTION
**Pull request by guo-shaoge**
### What problem does this PR solve?

Issue Number: close #6916

Problem Summary: As issued said, and we fix the second problem here of issue.

### What is changed and how it works?
Mainly changes are in client-c: https://github.com/tikv/client-c/pull/127
### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

**Comment by guo-shaoge** [comment]
fix here: https://github.com/pingcap/tiflash/pull/6920

**Pull request closed without merging**
