### PR TITLE
Add flag for ingest range check

### PR DESCRIPTION
**Pull request by breezewish**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflash/issues/7766

Problem Summary:

### What is changed and how it works?

Allow users to disable the range check in order to start TiFlash normally.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
just trigger /unhold when ready to merge

**Pull request merged**
