### PR TITLE
Fix logger initialization of DTWorkload.

### LINKED ISSUE #4636: DTWorkload tool failed to create a log file.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run `./tiflash dtworkload`.

### 2. What did you expect to see? (Required)

No error message.

### 3. What did you see instead (Required)

middle_img_v2_39e472d7-929c-42f6-a8f6-6bdaa07d657g

### 4. What is your TiFlash version? (Required)

master

### PR DESCRIPTION
**Pull request by JinheLin**
### What problem does this PR solve?

Issue Number: close #4636

Problem Summary:
DTWorkload's log file is created in the first directory if `opts.work_dirs` by default.
If `opts.work_dirs[0]` is not exist and no log file path(`--log_file`) is specified, logger initialization will fail.
So create these `work_dirs` before logger initialization.

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lidezhu — APPROVED** [review]
LGTM

**Review by JaySon-Huang — APPROVED** [review]
LGTM

Using the `Poco::File` API may be a more common way to do sth like this in TiFlash code. But `mkdir` is also ok.

**Pull request merged**
