### PR TITLE
Compat serverless FAP features including shard_ver, txn ref and enc key

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: ref #8673

Problem Summary:

Ref https://github.com/tidbcloud/tiflash-cse/pull/287.

We have to add some dummy implementations in TiFlash master, to reduce the divergence between serverless interfaces and codes.

The PR includes:
1. In Proxy, we update ProxyFFI.h for some changes. We also introduce a serverless_extra.rs file that does nothing as a stub file.
2. In TiFlash, we add and change some functions in FastAddPeer.cpp to support newly added interfaces. The newly add functions will always return empty(string or int). So there is little side effect.

### What is changed and how it works?

```commit-message
Compatibility for serverless FAP features including shard_ver, txn ref and enc key
```

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JaySon-Huang — COMMENTED** [review]
Generally LGTM

The changes in tiflash-proxy should be a formal commit on the raftstore-proxy branch?

**Comment by CalvinNeo** [comment]
> Generally LGTM
> 
> The changes in tiflash-proxy should be a formal commit on the raftstore-proxy branch?

Yes, Hold this PR until proxy's PR is merged

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Review by Lloyd-Pottiger — APPROVED** [review]

**Pull request merged**
