### PR TITLE
Improve performance of number comparison functions

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
### What problem does this PR solve?

Issue Number: ref #5672

Problem Summary:

### What is changed and how it works?
using dynamic dispatch
port from https://github.com/ClickHouse/ClickHouse/pull/37399

### Check List

Tests 

- [x] Unit test
- [x] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

### Result
```mysql
--before
mysql > select c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice, sum(l_quantity) from CUSTOMER, ORDERS, LINEITEM where o_orderkey in (         select l_orderkey         from LINEITEM
  group by l_orderkey         having sum(l_quantity) > 314     )     and c_custkey = o_custkey     and o_orderkey = l_orderkey group by c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice order by o_totalprice desc, o_orderdate limit 100;
+--------------------+-----------+------------+-------------+--------------+-----------------+
| c_name             | c_custkey | o_orderkey | o_orderdate | o_totalprice | sum(l_quantity) |
+--------------------+-----------+------------+-------------+--------------+-----------------+
| Customer#000128120 |    128120 |    4722021 | 1994-04-07  |    544089.09 |          323.00 |
| Customer#000144617 |    144617 |    3043270 | 1997-02-12  |    530604.44 |          317.00 |
| Customer#000066790 |     66790 |    2199712 | 1996-09-30  |    515531.82 |          327.00 |
| Customer#000015619 |     15619 |    3767271 | 1996-08-07  |    480083.96 |          318.00 |
| Customer#000147197 |    147197 |    1263015 | 1997-02-02  |    467149.67 |          320.00 |
| Customer#000117919 |    117919 |    2869152 | 1996-06-20  |    456815.92 |          317.00 |
| Customer#000126865 |    126865 |    4702759 | 1994-11-07  |    447606.65 |          320.00 |
| Customer#000036619 |     36619 |    4806726 | 1995-01-17  |    446704.09 |          328.00 |
| Customer#000119989 |    119989 |    1544643 | 1997-09-20  |    434568.25 |          320.00 |
+--------------------+-----------+------------+-------------+--------------+-----------------+
9 rows in set (4.40 sec)

-- after 
mysql > select c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice, sum(l_quantity) from CUSTOMER, ORDERS, LINEITEM where o_orderkey in (         select l_orderkey         from LINEITEM
  group by l_orderkey         having sum(l_quantity) > 314     )     and c_custkey = o_custkey     and o_orderkey = l_orderkey group by c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice order by o_totalprice desc, o_orderdate limit 100;
+--------------------+-----------+------------+-------------+--------------+-----------------+
| c_name             | c_custkey | o_orderkey | o_orderdate | o_totalprice | sum(l_quantity) |
+--------------------+-----------+------------+-------------+--------------+-----------------+
| Customer#000128120 |    128120 |    4722021 | 1994-04-07  |    544089.09 |          323.00 |
| Customer#000144617 |    144617 |    3043270 | 1997-02-12  |    530604.44 |          317.00 |
| Customer#000066790 |     66790 |    2199712 | 1996-09-30  |    515531.82 |          327.00 |
| Customer#000015619 |     15619 |    3767271 | 1996-08-07  |    480083.96 |          318.00 |
| Customer#000147197 |    147197 |    1263015 | 1997-02-02  |    467149.67 |          320.00 |
| Customer#000117919 |    117919 |    2869152 | 1996-06-20  |    456815.92 |          317.00 |
| Customer#000126865 |    126865 |    4702759 | 1994-11-07  |    447606.65 |          320.00 |
| Customer#000036619 |     36619 |    4806726 | 1995-01-17  |    446704.09 |          328.00 |
| Customer#000119989 |    119989 |    1544643 | 1997-09-20  |    434568.25 |          320.00 |
+--------------------+-----------+------------+-------------+--------------+-----------------+
9 rows in set (4.24 sec)
```

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by ywqzzy** [comment]
A solid bench is needed

**Comment by Lloyd-Pottiger** [comment]
```shell
Running ./dbms/bench_dbms
Run on (40 X 2399.94 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x20)
  L1 Instruction 32 KiB (x20)
  L2 Unified 256 KiB (x20)
  L3 Unified 25600 KiB (x2)
Load Average: 48.56, 24.48, 23.63
# before
--------------------------------------------------------------------------------------------------
Benchmark                                                        Time             CPU   Iterations
--------------------------------------------------------------------------------------------------
NumberComparsionBench/constantEqVector/iterations:100        95193 ns        95195 ns          100
NumberComparsionBench/vectorEqVector/iterations:100         112950 ns       112955 ns          100
NumberComparsionBench/constantLessVector/iterations:100     104847 ns       104850 ns          100
NumberComparsionBench/vectorLessVector/iterations:100       112402 ns       112410 ns          100
# after
--------------------------------------------------------------------------------------------------
Benchmark                                                        Time             CPU   Iterations
--------------------------------------------------------------------------------------------------
NumberComparsionBench/constantEqVector/iterations:100        60521 ns        60521 ns          100
NumberComparsionBench/vectorEqVector/iterations:100          63688 ns        63687 ns          100
NumberComparsionBench/constantLessVector/iterations:100      58405 ns        58405 ns          100
NumberComparsionBench/vectorLessVector/iterations:100        64027 ns        64028 ns          100
```

**Comment by Lloyd-Pottiger** [comment]
change the `row_num = 10000000`
```shell
# before
--------------------------------------------------------------------------------------------------
Benchmark                                                        Time             CPU   Iterations
--------------------------------------------------------------------------------------------------
NumberComparsionBench/constantEqVector/iterations:100     10734751 ns     10734228 ns          100
NumberComparsionBench/vectorEqVector/iterations:100       19793874 ns     19791053 ns          100
NumberComparsionBench/constantLessVector/iterations:100   11959062 ns     11947725 ns          100
NumberComparsionBench/vectorLessVector/iterations:100     19011253 ns     19001708 ns          100
# after
--------------------------------------------------------------------------------------------------
Benchmark                                                        Time             CPU   Iterations
--------------------------------------------------------------------------------------------------
NumberComparsionBench/constantEqVector/iterations:100      8810097 ns      8810259 ns          100
NumberComparsionBench/vectorEqVector/iterations:100       16357388 ns     16312559 ns          100
NumberComparsionBench/constantLessVector/iterations:100    9277899 ns      9278057 ns          100
NumberComparsionBench/vectorLessVector/iterations:100     15475154 ns     15475493 ns          100
```

**Review by windtalker — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]
Excellent

**Comment by Lloyd-Pottiger** [comment]
merge into #5748

**Pull request closed without merging**
