### PR TITLE
Fix asan test failed

### LINKED ISSUE #6841: Some asan test fail
## Bug Report

As shown in https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/885/pipeline

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #6841 

Problem Summary: There are some asan failure after running unit tests which was introduced by https://github.com/pingcap/tiflash/pull/6717. This is caused by unsuccessfully cleaning some objects after running unit tests.

### What is changed and how it works?
Do some clean work after running unit test.

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by Lloyd-Pottiger** [comment]
Should we make sure `UniversalPageStorageService` is shutdown when tiflash server is down?

**Comment by lidezhu** [comment]
> Should we make sure `UniversalPageStorageService` is shutdown when tiflash server is down?

It is done in `ContextShared::shutdown()`.

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Pull request merged**
