### PR TITLE
Optimize apply speed under heavy write pressure

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: ref #4728 

Problem Summary: When tiflash is under heavy write pressure, it will consume a lot of write throughput and cause some latency on the process of apply raft log, which will make tiflash consume a log memory.

### What is changed and how it works?
1. Only allow one delta flush process on a segment to process at any time to avoid unnecessary throughput consumption;
2. When processing `CompactLog` raft command, just try to flush the unsaved value in storage once and return `Persist` if the flush succed or `None` if the flush failed.(Originally we try to flush until it success)
3. Increase foreground flush threshold for write thread.
4. Avoid add minor compaction task to background if the segment is flushing to save some throughput and reduce lock contention on the segment.

### Check List

Tests 

- [x] Manual test (add detailed scripts or steps below)
Test step:
1. perform large transaction update through 5 tidb instance at the same time and the total transaction size of all tidb instance is about 24.5 GB;
Before optimize:
image
After optimize:
image

Detail result(unit: GB)
  | 1st run | 2nd run | 3rd run | 4th run | 5th run | 6th run) | 7th run | average value | amplification factor
-- | -- | -- | -- | -- | -- | --| -- | -- | --
before optimization | 40.8 | 37.2 | 37.3 | 36 | 34.7 | 33.6 | 34.5 | 36.3 | 1.48
after optimization | 38.1 | 29.4 | 29 | 34.3 | 29.6 | 32.6 | 37.7 | 32.9 | 1.34

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by flowbehappy — APPROVED** [review]
LGTM

**Comment by flowbehappy** [comment]
Can you add some metrics to show the result of this optimization? @lidezhu

**Comment by lidezhu** [comment]
> Can you add some metrics to show the result of this optimization? @lidezhu

Done

**Review by CalvinNeo — APPROVED** [review]
LGTM

**Pull request merged**
