### PR TITLE
Fix gtest_dm_minmax_index.cpp clang tidy.

### LINKED ISSUE #4603: Fix clang-tidy error in `dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp`
## Enhancement
```
clang-tidy -p=/home/finder/projects/tiflash/build/ /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp
/home/finder/projects/tiflash/contrib/boost/boost/config/detail/select_stdlib_config.hpp:26:14: error: 'cstddef' file not found [clang-diagnostic-error]
#    include <cstddef>
             ^
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:47:23: error: method 'abandon' can be made static [readability-convert-member-functions-to-static,-warnings-as-errors]
void DeltaValueSpace::abandon(DMContext & context)
                      ^
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:71:60: error: parameter 'head_column_files' is unused [misc-unused-parameters,-warnings-as-errors]
                                       const ColumnFiles & head_column_files,
                                                           ^~~~~~~~~~~~~~~~~
                                                            /*head_column_files*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:102:23: error: method 'appendColumnFile' can be made static [readability-convert-member-functions-to-static,-warnings-as-errors]
bool DeltaValueSpace::appendColumnFile(DMContext & /*context*/, const ColumnFilePtr & column_file)
                      ^
static 
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:102:87: error: parameter 'column_file' is unused [misc-unused-parameters,-warnings-as-errors]
bool DeltaValueSpace::appendColumnFile(DMContext & /*context*/, const ColumnFilePtr & column_file)
                                                                                      ^~~~~~~~~~~
                                                                                       /*column_file*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:106:16: error: redundant boolean literal in conditional return statement [readability-simplify-boolean-expr,-warnings-as-errors]
        return false;
~~~~~~~~~~~~~~~^~~~~~
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:112:23: error: method 'appendToCache' can be made static [readability-convert-member-functions-to-static,-warnings-as-errors]
bool DeltaValueSpace::appendToCache(DMContext & context, const Block & block, size_t offset, size_t limit)
                      ^
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:116:16: error: redundant boolean literal in conditional return statement [readability-simplify-boolean-expr,-warnings-as-errors]
        return false;
~~~~~~~~~~~~~~~^~~~~~
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:122:23: error: method 'appendDeleteRange' can be made static [readability-convert-member-functions-to-static,-warnings-as-errors]
bool DeltaValueSpace::appendDeleteRange(DMContext & /*context*/, const RowKeyRange & delete_range)
                      ^
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:126:16: error: redundant boolean literal in conditional return statement [readability-simplify-boolean-expr,-warnings-as-errors]
        return false;
~~~~~~~~~~~~~~~^~~~~~
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:132:23: error: method 'ingestColumnFiles' can be made static [readability-convert-member-functions-to-static,-warnings-as-errors]
bool DeltaValueSpace::ingestColumnFiles(DMContext & /*context*/, const RowKeyRange & range, const ColumnFiles & column_files, bool clear_data_in_range)
                      ^
static 
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:132:113: error: parameter 'column_files' is unused [misc-unused-parameters,-warnings-as-errors]
bool DeltaValueSpace::ingestColumnFiles(DMContext & /*context*/, const RowKeyRange & range, const ColumnFiles & column_files, bool clear_data_in_range)
                                                                                                                ^~~~~~~~~~~~
                                                                                                                 /*column_files*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp:136:16: error: redundant boolean literal in conditional return statement [readability-simplify-boolean-expr,-warnings-as-errors]
        return false;
~~~~~~~~~~~~~~~^~~~~~
32812 warnings and 1 error generated.
Error while processing /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/Delta/DeltaValueSpace.cpp.
Suppressed 32819 warnings (32800 in non-user code, 19 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
12 warnings treated as errors
```

### LINKED ISSUE #4604: Fix clang-tidy error in `dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp`
## Enhancement
```
clang-tidy -p=/home/finder/projects/tiflash/build/ /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp
/home/finder/projects/tiflash/contrib/libcityhash/include/city.h:48:10: error: 'utility' file not found [clang-diagnostic-error]
#include <utility>
         ^
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:44:5: error: use '= default' to define a trivial default constructor [modernize-use-equals-default,-warnings-as-errors]
    DMMinMaxIndexTest() {}
    ^                   ~~
                        = default;
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:47:17: error: invalid case style for method 'SetUpTestCase' [readability-identifier-naming,-warnings-as-errors]
    static void SetUpTestCase() {}
                ^~~~~~~~~~~~~
                setUpTestCase
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:49:10: error: method 'SetUp' can be made static [readability-convert-member-functions-to-static,-warnings-as-errors]
    void SetUp() override
         ^
    static 
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:49:10: error: invalid case style for method 'SetUp' [readability-identifier-naming,-warnings-as-errors]
    void SetUp() override
         ^~~~~
         setUp
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:58:10: error: invalid case style for method 'TearDown' [readability-identifier-naming,-warnings-as-errors]
    void TearDown() override
         ^~~~~~~~
         tearDown
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:81:20: error: parameter 'test_case' is unused [misc-unused-parameters,-warnings-as-errors]
    const String & test_case,
                   ^~~~~~~~~
                    /*test_case*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:83:20: error: parameter 'type' is unused [misc-unused-parameters,-warnings-as-errors]
    const String & type,
                   ^~~~
                    /*type*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:84:21: error: parameter 'block_tuples' is unused [misc-unused-parameters,-warnings-as-errors]
    const CSVTuples block_tuples,
                    ^~~~~~~~~~~~
                     /*block_tuples*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:85:27: error: parameter 'filter' is unused [misc-unused-parameters,-warnings-as-errors]
    const RSOperatorPtr & filter,
                          ^~~~~~
                           /*filter*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:136:32: error: parameter 'test_case' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                               ^~~~~~~~~
                                /*test_case*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:136:77: error: parameter 'type' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                                                            ^~~~
                                                                             /*type*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:136:98: error: parameter 'value' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                                                                                 ^~~~~
                                                                                                  /*value*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:136:127: error: parameter 'filter' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                                                                                                              ^~~~~~
                                                                                                                               /*filter*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:144:35: error: parameter 'test_case' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkDelMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                  ^~~~~~~~~
                                   /*test_case*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:144:80: error: parameter 'type' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkDelMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                                                               ^~~~
                                                                                /*type*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:144:101: error: parameter 'value' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkDelMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                                                                                    ^~~~~
                                                                                                     /*value*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:144:130: error: parameter 'filter' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkDelMatch(const String & test_case, Context & context, const String & type, const String & value, const RSOperatorPtr & filter)
                                                                                                                                 ^~~~~~
                                                                                                                                  /*filter*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:152:34: error: parameter 'test_case' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkPkMatch(const String & test_case, Context & context, const String & type, const String & pk_value, const RSOperatorPtr & filter, bool is_common_handle)
                                 ^~~~~~~~~
                                  /*test_case*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:152:79: error: parameter 'type' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkPkMatch(const String & test_case, Context & context, const String & type, const String & pk_value, const RSOperatorPtr & filter, bool is_common_handle)
                                                                              ^~~~
                                                                               /*type*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:152:100: error: parameter 'pk_value' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkPkMatch(const String & test_case, Context & context, const String & type, const String & pk_value, const RSOperatorPtr & filter, bool is_common_handle)
                                                                                                   ^~~~~~~~
                                                                                                    /*pk_value*/
/home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp:152:132: error: parameter 'filter' is unused [misc-unused-parameters,-warnings-as-errors]
bool checkPkMatch(const String & test_case, Context & context, const String & type, const String & pk_value, const RSOperatorPtr & filter, bool is_common_handle)
                                                                                                                                   ^~~~~~
                                                                                                                                    /*filter*/
49991 warnings and 1 error generated.
Error while processing /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp.
99986 warnings and 2 errors generated.
Error while processing /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp.
149981 warnings and 3 errors generated.
Error while processing /home/finder/projects/tiflash/dbms/src/Storages/DeltaMerge/tests/gtest_dm_minmax_index.cpp.
Suppressed 150062 warnings (149918 in non-user code, 144 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
21 warnings treated as errors
```

### PR DESCRIPTION
**Pull request by cakebytheoceanLuo**
Signed-off-by: Jigao Luo <luojigao@outlook.com>

### What problem does this PR solve?

Issue Number: close #4604 

Problem Summary:

### Check List

Tests 

- [x] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
@cakebytheoceanLuo Thanks for your contribution!

**Review by SeaRise — APPROVED** [review]
LGTM

**Review by ywqzzy — APPROVED** [review]
LGTM

**Pull request merged**
